import { Locale } from 'src/common/constants/locales';
import { pickTranslation } from 'src/common/utils';
import { ViolationResponse } from '../dto/responses/violation.response';
import { Violation } from '../entities/violation.entity';

export function toViolationResponse(violation: Violation, locale: Locale): ViolationResponse {
  const type = violation.violationType;

  return {
    id: violation.id,
    type: {
      id: type.id,
      code: type.code,
      name: pickTranslation(type.translations, locale)?.name ?? type.code,
      defaultSeverity: type.defaultSeverity,
    },
    user: { id: violation.user.id, fullName: violation.user.fullName },
    machine: violation.machine
      ? { id: violation.machine.id, serial: violation.machine.serial }
      : null,
    transferId: violation.transferId,
    severity: violation.severity,
    status: violation.status,
    description: violation.description,
    chargedAmount: violation.chargedAmount === null ? null : Number(violation.chargedAmount),
    chargedAt: violation.chargedAt?.toISOString() ?? null,
    waiverReason: violation.waiverReason,
    acknowledgedAt: violation.acknowledgedAt?.toISOString() ?? null,
    resolvedAt: violation.resolvedAt?.toISOString() ?? null,
    autoGenerated: violation.autoGenerated,
    // Sent so the app can grey out the edit button rather than offer it and take a 422.
    isEditable: !violation.autoGenerated,
    createdAt: violation.createdAt.toISOString(),
  };
}
