import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from 'src/common/entities/base.entity';
import { Severity, ViolationStatus } from 'src/common/enums/operations.enum';
import { Branch } from 'src/modules/organization/entities/branch.entity';
import { Machine } from 'src/modules/machines/entities/machine.entity';
import { PaymentMethod } from 'src/modules/lookups/entities/payment-method.entity';
import { Transfer } from 'src/modules/transfers/entities/transfer.entity';
import { TransferItem } from 'src/modules/transfers/entities/transfer-item.entity';
import { User } from 'src/modules/users/entities/user.entity';
import { ViolationType } from 'src/modules/lookups/entities/violation-type.entity';

/**
 * A line on a representative's disciplinary file.
 *
 * Violations are never deleted — only waived, with a reason. That is the whole reason the table
 * exists: a record a supervisor can quietly remove is not a record, and the same argument would
 * then be had again next month with no evidence either way.
 *
 * `autoGenerated` rows come from the return-leg checks in `violation-rules.ts` and cannot be
 * edited, only waived or charged. The comparison they were drawn from lives on `transferItemId`,
 * which is also what the unique index uses to make a replayed confirm a no-op.
 */
@Entity('violations')
@Index('idx_violations_user_status', ['userId', 'status'])
@Index('idx_violations_machine_id', ['machineId'])
@Index('idx_violations_branch_id', ['branchId'])
export class Violation extends BaseEntity {
  @Column({ name: 'violation_type_id', type: 'uuid' })
  violationTypeId: string;

  /** Who is held responsible. A violation is always attached to a person (`10`, rule 2). */
  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  @Column({ name: 'machine_id', type: 'uuid', nullable: true })
  machineId: string | null;

  @Column({ name: 'transfer_id', type: 'uuid', nullable: true })
  transferId: string | null;

  @Column({ name: 'transfer_item_id', type: 'uuid', nullable: true })
  transferItemId: string | null;

  @Column({ name: 'branch_id', type: 'uuid', nullable: true })
  branchId: string | null;

  @Column({ type: 'varchar', length: 10 })
  severity: Severity;

  @Column({ type: 'text' })
  description: string;

  @Column({ type: 'varchar', length: 20, default: ViolationStatus.OPEN })
  status: ViolationStatus;

  @Column({ name: 'charged_amount', type: 'numeric', precision: 14, scale: 2, nullable: true })
  chargedAmount: string | null;

  @Column({ name: 'payment_method_id', type: 'uuid', nullable: true })
  paymentMethodId: string | null;

  @Column({ name: 'charged_at', type: 'timestamptz', nullable: true })
  chargedAt: Date | null;

  /** The income row this charge produced. Null until it is charged, and never null after. */
  @Column({ name: 'finance_transaction_id', type: 'uuid', nullable: true })
  financeTransactionId: string | null;

  @Column({ name: 'waiver_reason', type: 'text', nullable: true })
  waiverReason: string | null;

  /** Set the first time the representative opens it in the app. */
  @Column({ name: 'acknowledged_at', type: 'timestamptz', nullable: true })
  acknowledgedAt: Date | null;

  @Column({ name: 'resolved_by_user_id', type: 'uuid', nullable: true })
  resolvedByUserId: string | null;

  @Column({ name: 'resolved_at', type: 'timestamptz', nullable: true })
  resolvedAt: Date | null;

  @Column({ name: 'auto_generated', type: 'boolean', default: false })
  autoGenerated: boolean;

  /** Generated on the device before the request leaves it; the offline dedupe key (`20`). */
  @Column({ name: 'client_uuid', type: 'uuid', nullable: true, unique: true })
  clientUuid: string | null;

  @ManyToOne(() => ViolationType, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'violation_type_id' })
  violationType: ViolationType;

  @ManyToOne(() => User, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @ManyToOne(() => Machine, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'machine_id' })
  machine: Machine | null;

  @ManyToOne(() => Transfer, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'transfer_id' })
  transfer: Transfer | null;

  @ManyToOne(() => TransferItem, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'transfer_item_id' })
  transferItem: TransferItem | null;

  @ManyToOne(() => Branch, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'branch_id' })
  branch: Branch | null;

  @ManyToOne(() => PaymentMethod, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'payment_method_id' })
  paymentMethod: PaymentMethod | null;

  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn({ name: 'resolved_by_user_id' })
  resolvedBy: User | null;
}
