import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsIn,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  MaxLength,
  Min,
  MinLength,
  Max,
} from 'class-validator';
import { MAX_MONEY_AMOUNT } from 'src/common/constants/money';
import { PaginationDto } from 'src/common/dto/pagination.dto';
import { toBoolean } from 'src/common/dto/query.dto';
import {
  SEVERITIES,
  Severity,
  VIOLATION_STATUSES,
  ViolationStatus,
} from 'src/common/enums/operations.enum';

/** Coerces `?status=OPEN` and `?status[]=OPEN&status[]=CHARGED` to the same array. */
const toArray = ({ value }: { value: unknown }): unknown =>
  value === undefined ? undefined : Array.isArray(value) ? value : [value];

export class CreateViolationDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  violationTypeId: string;

  @ApiProperty({ format: 'uuid', description: 'Who is held responsible.' })
  @IsUUID()
  userId: string;

  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  machineId?: string;

  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  transferItemId?: string;

  @ApiProperty({ enum: SEVERITIES })
  @IsIn(SEVERITIES)
  severity: Severity;

  @ApiProperty({ maxLength: 1000 })
  @IsString()
  @MinLength(5)
  @MaxLength(1000)
  description: string;

  @ApiPropertyOptional({
    format: 'uuid',
    description: 'Device-generated id. Re-sending it returns the violation already filed.',
  })
  @IsOptional()
  @IsUUID()
  clientUuid?: string;
}

/**
 * Only the two fields a reviewer legitimately revises. Auto-generated rows reject even these
 * (`AUTO_VIOLATION_IMMUTABLE`) — a detected mismatch that can be edited afterwards is not
 * evidence of anything.
 */
export class UpdateViolationDto {
  @ApiPropertyOptional({ enum: SEVERITIES })
  @IsOptional()
  @IsIn(SEVERITIES)
  severity?: Severity;

  @ApiPropertyOptional({ maxLength: 1000 })
  @IsOptional()
  @IsString()
  @MinLength(5)
  @MaxLength(1000)
  description?: string;

  @ApiPropertyOptional({
    enum: [ViolationStatus.ACKNOWLEDGED, ViolationStatus.CLOSED],
    description: 'Only forward moves that do not involve money.',
  })
  @IsOptional()
  @IsIn([ViolationStatus.ACKNOWLEDGED, ViolationStatus.CLOSED])
  status?: ViolationStatus;
}

export class ChargeViolationDto {
  @ApiProperty({ example: 250 })
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0.01)
  @Max(MAX_MONEY_AMOUNT)
  amount: number;

  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  paymentMethodId: string;

  @ApiProperty({ example: '2026-09-08T10:00:00.000Z' })
  @IsDateString()
  chargedAt: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @Length(1, 1000)
  notes?: string;
}

export class WaiveViolationDto {
  @ApiProperty({ minLength: 5, maxLength: 500 })
  @IsString()
  @MinLength(5)
  @MaxLength(500)
  reason: string;
}

export const VIOLATION_SORT_FIELDS = ['createdAt', 'severity', 'status'] as const;

export type ViolationSortField = (typeof VIOLATION_SORT_FIELDS)[number];

export class QueryViolationsDto extends PaginationDto {
  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  userId?: string;

  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  machineId?: string;

  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  typeId?: string;

  @ApiPropertyOptional({ format: 'uuid' })
  @IsOptional()
  @IsUUID()
  branchId?: string;

  @ApiPropertyOptional({ enum: SEVERITIES, isArray: true })
  @IsOptional()
  @Transform(toArray)
  @IsArray()
  @IsIn(SEVERITIES, { each: true })
  severity?: Severity[];

  @ApiPropertyOptional({ enum: VIOLATION_STATUSES, isArray: true })
  @IsOptional()
  @Transform(toArray)
  @IsArray()
  @IsIn(VIOLATION_STATUSES, { each: true })
  status?: ViolationStatus[];

  @ApiPropertyOptional({ example: '2026-01-01' })
  @IsOptional()
  @IsDateString()
  dateFrom?: string;

  @ApiPropertyOptional({ example: '2026-12-31' })
  @IsOptional()
  @IsDateString()
  dateTo?: string;

  @ApiPropertyOptional({ description: 'Only rows the return-leg detector raised.' })
  @IsOptional()
  @Transform(toBoolean)
  @IsBoolean()
  autoGenerated?: boolean;

  @ApiPropertyOptional({ enum: VIOLATION_SORT_FIELDS, default: 'createdAt' })
  @IsOptional()
  @IsIn(VIOLATION_SORT_FIELDS)
  sortBy: ViolationSortField = 'createdAt';
}
