/**
 * Semantic action codes recorded by `AuditService.record()` (`21`). One per meaningfully
 * distinct thing that can happen to an entity — not one per HTTP verb, so the log reads like a
 * history rather than a request trace.
 */
export enum AuditAction {
  MACHINE_CREATED = 'MACHINE_CREATED',
  MACHINE_UPDATED = 'MACHINE_UPDATED',
  BATTERY_CREATED = 'BATTERY_CREATED',
  BATTERY_UPDATED = 'BATTERY_UPDATED',

  MERCHANT_CREATED = 'MERCHANT_CREATED',
  MERCHANT_UPDATED = 'MERCHANT_UPDATED',
  MERCHANT_DEACTIVATED = 'MERCHANT_DEACTIVATED',

  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_PERMISSIONS_UPDATED = 'USER_PERMISSIONS_UPDATED',

  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_PERMISSIONS_UPDATED = 'ROLE_PERMISSIONS_UPDATED',

  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  BRANCH_DEACTIVATED = 'BRANCH_DEACTIVATED',
  BRANCH_ACTIVATED = 'BRANCH_ACTIVATED',
  WAREHOUSE_CREATED = 'WAREHOUSE_CREATED',

  TRANSFER_CREATED = 'TRANSFER_CREATED',
  TRANSFER_CONFIRMED = 'TRANSFER_CONFIRMED',
  TRANSFER_REJECTED = 'TRANSFER_REJECTED',
  TRANSFER_CANCELLED = 'TRANSFER_CANCELLED',
  TRANSFER_SIGNATURE_CAPTURED = 'TRANSFER_SIGNATURE_CAPTURED',

  MAINTENANCE_CREATED = 'MAINTENANCE_CREATED',
  MAINTENANCE_UPDATED = 'MAINTENANCE_UPDATED',
  MAINTENANCE_SENT = 'MAINTENANCE_SENT',
  MAINTENANCE_RECEIVED = 'MAINTENANCE_RECEIVED',
  MAINTENANCE_CLOSED = 'MAINTENANCE_CLOSED',
  MAINTENANCE_CANCELLED = 'MAINTENANCE_CANCELLED',

  MACHINE_REPLACED = 'MACHINE_REPLACED',
  MACHINE_DECOMMISSIONED = 'MACHINE_DECOMMISSIONED',
  DECOMMISSION_REVERTED = 'DECOMMISSION_REVERTED',

  FINANCE_TRANSACTION_CREATED = 'FINANCE_TRANSACTION_CREATED',
  FINANCE_TRANSACTION_UPDATED = 'FINANCE_TRANSACTION_UPDATED',
  FINANCE_TRANSACTION_VOIDED = 'FINANCE_TRANSACTION_VOIDED',
  FINANCE_READ_ACCESSED = 'FINANCE_READ_ACCESSED',

  BUDGET_CREATED = 'BUDGET_CREATED',
  BUDGET_UPDATED = 'BUDGET_UPDATED',
  BUDGET_DELETED = 'BUDGET_DELETED',

  FINANCE_CATEGORY_CREATED = 'FINANCE_CATEGORY_CREATED',
  FINANCE_CATEGORY_UPDATED = 'FINANCE_CATEGORY_UPDATED',
  FINANCE_CATEGORY_MOVED = 'FINANCE_CATEGORY_MOVED',
  FINANCE_CATEGORY_DELETED = 'FINANCE_CATEGORY_DELETED',

  VIOLATION_CREATED = 'VIOLATION_CREATED',
  VIOLATION_ACKNOWLEDGED = 'VIOLATION_ACKNOWLEDGED',
  VIOLATION_UPDATED = 'VIOLATION_UPDATED',
  VIOLATION_CHARGED = 'VIOLATION_CHARGED',
  VIOLATION_WAIVED = 'VIOLATION_WAIVED',

  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  BIOMETRIC_ENROLLED = 'BIOMETRIC_ENROLLED',
}

/** What `entityType` names on an audit row. Kept as plain strings in the column (no DB check
 * constraint) so a new entity type never needs a migration — this union is the compile-time
 * guard instead. */
export enum AuditEntityType {
  MACHINE = 'machine',
  BATTERY = 'battery',
  MERCHANT = 'merchant',
  USER = 'user',
  ROLE = 'role',
  BRANCH = 'branch',
  WAREHOUSE = 'warehouse',
  TRANSFER = 'transfer',
  TRANSFER_SIGNATURE = 'transfer_signature',
  MAINTENANCE_ORDER = 'maintenance_order',
  REPLACEMENT = 'replacement',
  DECOMMISSION = 'decommission',
  FINANCE_TRANSACTION = 'finance_transaction',
  BUDGET = 'budget',
  FINANCE_CATEGORY = 'finance_category',
  VIOLATION = 'violation',
  AUTH = 'auth',
  FINANCE = 'finance',
}
