import 'package:machinery/core/constants/api_keys.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';

/// `GET /violations`, `GET /violations/:id` and every action endpoint, which all
/// answer with the same row.
class ViolationResponseModel {
  const ViolationResponseModel({required this.entity});

  final ViolationEntity entity;

  factory ViolationResponseModel.fromJson(Map<String, dynamic> json) {
    final Map<String, dynamic> type = _object(json[ApiKeys.type]);
    final Map<String, dynamic> user = _object(json[ApiKeys.user]);
    final Map<String, dynamic> machine = _object(json[ApiKeys.machine]);

    return ViolationResponseModel(
      entity: ViolationEntity(
        id: json[ApiKeys.id]?.toString() ?? '',
        type: ViolationTypeRef(
          id: type[ApiKeys.id]?.toString() ?? '',
          code: type[ApiKeys.code] as String? ?? '',
          name: type[ApiKeys.name] as String? ?? '',
          defaultSeverity: ViolationSeverity.fromJson(
            type[ApiKeys.defaultSeverity] as String?,
          ),
        ),
        user: ViolationUserRef(
          id: user[ApiKeys.id]?.toString() ?? '',
          fullName: user[ApiKeys.fullName] as String? ?? '',
        ),
        machine: machine.isEmpty
            ? null
            : ViolationMachineRef(
                id: machine[ApiKeys.id]?.toString() ?? '',
                serial: machine[ApiKeys.serial] as String? ?? '',
              ),
        transferId: json[ApiKeys.transferId]?.toString(),
        severity: ViolationSeverity.fromJson(json[ApiKeys.severity] as String?),
        status: ViolationStatus.fromJson(json[ApiKeys.status] as String?),
        description: json[ApiKeys.description] as String? ?? '',
        chargedAmount: _double(json[ApiKeys.chargedAmount]),
        chargedAt: _dateOrNull(json[ApiKeys.chargedAt]),
        waiverReason: json[ApiKeys.waiverReason] as String?,
        acknowledgedAt: _dateOrNull(json[ApiKeys.acknowledgedAt]),
        resolvedAt: _dateOrNull(json[ApiKeys.resolvedAt]),
        createdAt: _dateOrNull(json[ApiKeys.createdAt]),
        autoGenerated: json[ApiKeys.autoGenerated] as bool? ?? false,
        // Defaulting to false locks the row rather than offering an edit the
        // server would refuse — the safer way to be wrong.
        isEditable: json[ApiKeys.isEditable] as bool? ?? false,
      ),
    );
  }

  ViolationEntity toEntity() => entity;

  static Map<String, dynamic> _object(dynamic raw) =>
      raw is Map<String, dynamic> ? raw : const <String, dynamic>{};

  /// `pg` sends `numeric` columns as strings so no precision is lost in
  /// transit, and JSON numbers arrive as `int` when they happen to be whole.
  static double? _double(dynamic value) {
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value);
    return null;
  }

  /// A malformed timestamp must not take the whole list down with it.
  static DateTime? _dateOrNull(dynamic value) {
    if (value is! String || value.isEmpty) return null;
    return DateTime.tryParse(value)?.toLocal();
  }
}

class ViolationSummaryModel {
  const ViolationSummaryModel({required this.summary});

  final ViolationSummary summary;

  factory ViolationSummaryModel.fromJson(Map<String, dynamic> json) {
    final Map<String, dynamic> user = ViolationResponseModel._object(
      json[ApiKeys.user],
    );
    final Map<String, dynamic> totals = ViolationResponseModel._object(
      json[ApiKeys.totals],
    );
    final Map<String, dynamic> bySeverity = ViolationResponseModel._object(
      json[ApiKeys.bySeverity],
    );

    return ViolationSummaryModel(
      summary: ViolationSummary(
        user: ViolationUserRef(
          id: user[ApiKeys.id]?.toString() ?? '',
          fullName: user[ApiKeys.fullName] as String? ?? '',
        ),
        branch: json[ApiKeys.branch] as String?,
        totals: ViolationTotals(
          all: _int(totals[ApiKeys.all]),
          open: _int(totals[ApiKeys.open]),
          charged: _int(totals[ApiKeys.charged]),
          waived: _int(totals[ApiKeys.waived]),
        ),
        byType: _rows(json[ApiKeys.byType])
            .map(
              (Map<String, dynamic> row) => ViolationTypeCount(
                code: row[ApiKeys.code] as String? ?? '',
                name: row[ApiKeys.name] as String? ?? '',
                count: _int(row[ApiKeys.count]),
                chargedAmount:
                    ViolationResponseModel._double(
                      row[ApiKeys.chargedAmount],
                    ) ??
                    0,
              ),
            )
            .toList(growable: false),
        // Keyed by the wire value, so an unrecognised severity is dropped
        // rather than collapsing several buckets into `unknown`.
        bySeverity: <ViolationSeverity, int>{
          for (final MapEntry<String, dynamic> entry in bySeverity.entries)
            if (ViolationSeverity.fromJson(entry.key) !=
                ViolationSeverity.unknown)
              ViolationSeverity.fromJson(entry.key): _int(entry.value),
        },
        totalCharged:
            ViolationResponseModel._double(json[ApiKeys.totalCharged]) ?? 0,
        last12Months: _rows(json[ApiKeys.last12Months])
            .map(
              (Map<String, dynamic> row) => ViolationMonthCount(
                month: row[ApiKeys.month] as String? ?? '',
                count: _int(row[ApiKeys.count]),
              ),
            )
            .toList(growable: false),
        trend: ViolationTrend.fromJson(json[ApiKeys.trend] as String?),
      ),
    );
  }

  ViolationSummary toEntity() => summary;

  static int _int(dynamic value) {
    if (value is int) return value;
    if (value is num) return value.toInt();
    if (value is String) return int.tryParse(value) ?? 0;
    return 0;
  }

  static List<Map<String, dynamic>> _rows(dynamic raw) {
    return raw is List
        ? raw.whereType<Map<String, dynamic>>().toList(growable: false)
        : const <Map<String, dynamic>>[];
  }
}
