'use client';

import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  Ban,
  CheckCircle2,
  Circle,
  Eye,
  Wallet,
} from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useMemo } from 'react';
import { z } from 'zod';

import { Can } from '@/components/common/can';
import { DateText } from '@/components/common/date-text';
import { Money } from '@/components/common/money';
import { SerialText } from '@/components/common/serial-text';
import { StatusChip } from '@/components/common/status-chip';
import { UserChip } from '@/components/common/user-chip';
import { DataTable, type DataTableColumn } from '@/components/data-table/data-table';
import { EmptyState } from '@/components/feedback/empty-state';
import { PageHeader } from '@/components/feedback/page-header';
import {
  BooleanFilter,
  BranchFilter,
  DateRangeFilter,
  FilterBar,
  LookupFilter,
  SelectFilter,
} from '@/components/filter-bar/filter-bar';
import { Link } from '@/i18n/navigation';
import { endpoints } from '@/lib/api/endpoints';
import { can } from '@/lib/auth/can';
import { P } from '@/lib/auth/permissions';
import { useSession } from '@/lib/auth/use-session';
import { useUrlFilters } from '@/lib/query/hooks';
import { SEVERITY_TONE, VIOLATION_STATUS_TONE } from '@/lib/theme/status-tone';

import { useViolationsList } from '../hooks/use-violations';
import {
  asNumber,
  type Violation,
  type ViolationSeverity,
  type ViolationStatus,
} from '../model/types';

const filtersSchema = z.object({
  status: z.union([z.string(), z.array(z.string())]).optional(),
  severity: z.union([z.string(), z.array(z.string())]).optional(),
  typeId: z.string().optional(),
  userId: z.string().optional(),
  branchId: z.string().optional(),
  dateFrom: z.string().optional(),
  dateTo: z.string().optional(),
  autoGenerated: z.union([z.boolean(), z.string()]).optional(),
  page: z.coerce.number().optional(),
  limit: z.coerce.number().optional(),
  sortDir: z.enum(['asc', 'desc']).optional(),
  sortBy: z.string().optional(),
});

const defaults = {
  page: 1,
  limit: 20,
  sortDir: 'desc' as const,
  sortBy: 'createdAt' as const,
};

function normalizeList(value: string | string[] | undefined): string[] | undefined {
  if (!value) return undefined;
  return Array.isArray(value) ? value : [value];
}

function toBool(value: unknown): boolean | undefined {
  if (value === true || value === 'true') return true;
  if (value === false || value === 'false') return false;
  return undefined;
}

const STATUS_ICON: Record<ViolationStatus, LucideIcon> = {
  OPEN: AlertCircle,
  ACKNOWLEDGED: Eye,
  WAIVED: Ban,
  CHARGED: Wallet,
  CLOSED: CheckCircle2,
};

const SEVERITY_ICON: Record<ViolationSeverity, LucideIcon> = {
  LOW: Circle,
  MEDIUM: AlertCircle,
  HIGH: AlertCircle,
};

export function ViolationsListPage() {
  const t = useTranslations();
  const { permissions } = useSession();
  const [filters, setFilters, reset] = useUrlFilters(filtersSchema, defaults);

  const listParams = useMemo(
    () => ({
      page: filters.page,
      limit: filters.limit,
      sortDir: filters.sortDir,
      sortBy:
        filters.sortBy === 'severity' || filters.sortBy === 'status' || filters.sortBy === 'createdAt'
          ? filters.sortBy
          : 'createdAt',
      status: normalizeList(filters.status),
      severity: normalizeList(filters.severity),
      typeId: filters.typeId,
      userId: filters.userId,
      branchId: filters.branchId,
      dateFrom: filters.dateFrom,
      dateTo: filters.dateTo,
      autoGenerated: toBool(filters.autoGenerated),
    }),
    [filters],
  );

  const query = useViolationsList(listParams);
  const canSeeMoney = can(permissions, P.financeRead);

  const hasActiveFilters = Boolean(
    filters.status ||
      filters.severity ||
      filters.typeId ||
      filters.userId ||
      filters.branchId ||
      filters.dateFrom ||
      filters.dateTo ||
      filters.autoGenerated === true ||
      filters.autoGenerated === 'true' ||
      filters.autoGenerated === false ||
      filters.autoGenerated === 'false',
  );

  const statusOptions = useMemo(
    () =>
      (['OPEN', 'ACKNOWLEDGED', 'WAIVED', 'CHARGED', 'CLOSED'] as const).map((value) => ({
        value,
        label: t(`enums.violationStatus.${value}`),
      })),
    [t],
  );

  const severityOptions = useMemo(
    () =>
      (['LOW', 'MEDIUM', 'HIGH'] as const).map((value) => ({
        value,
        label: t(`enums.severity.${value}`),
      })),
    [t],
  );

  const columns = useMemo<DataTableColumn<Violation>[]>(() => {
    const cols: DataTableColumn<Violation>[] = [
      {
        id: 'type',
        accessorFn: (row) => row.type.name,
        header: t('web.violations.type'),
        meta: { label: t('web.violations.type'), locked: true },
        cell: ({ row }) => (
          <div className="min-w-0 space-y-xs">
            <p className="truncate font-medium">{row.original.type.name}</p>
            {row.original.autoGenerated ? (
              <StatusChip
                tone="info"
                icon={AlertCircle}
                label={t('shared.violation_auto_badge')}
              />
            ) : null}
          </div>
        ),
      },
      {
        id: 'severity',
        accessorKey: 'severity',
        header: t('web.violations.severity'),
        meta: { label: t('web.violations.severity') },
        cell: ({ row }) => {
          const severity = row.original.severity;
          return (
            <StatusChip
              status={severity}
              tone={SEVERITY_TONE[severity] ?? 'neutral'}
              icon={SEVERITY_ICON[severity] ?? Circle}
              label={t(`enums.severity.${severity}` as 'enums.severity.UNKNOWN')}
            />
          );
        },
      },
      {
        id: 'status',
        accessorKey: 'status',
        header: t('web.violations.status'),
        meta: { label: t('web.violations.status') },
        cell: ({ row }) => {
          const status = row.original.status;
          return (
            <StatusChip
              status={status}
              tone={VIOLATION_STATUS_TONE[status] ?? 'neutral'}
              icon={STATUS_ICON[status] ?? Circle}
              label={t(`enums.violationStatus.${status}` as 'enums.violationStatus.UNKNOWN')}
            />
          );
        },
      },
      {
        id: 'user',
        enableSorting: false,
        header: t('web.violations.subject'),
        meta: { label: t('web.violations.subject') },
        cell: ({ row }) => <UserChip user={row.original.user} />,
      },
      {
        id: 'machine',
        enableSorting: false,
        header: t('web.violations.machine'),
        meta: { label: t('web.violations.machine') },
        cell: ({ row }) => {
          const serial = row.original.machine?.serial;
          return serial ? <SerialText value={serial} /> : <span className="text-text-secondary">—</span>;
        },
      },
    ];

    if (canSeeMoney) {
      cols.push({
        id: 'amount',
        enableSorting: false,
        header: t('web.violations.amount'),
        meta: { label: t('web.violations.amount') },
        cell: ({ row }) => <Money value={asNumber(row.original.chargedAmount)} />,
      });
    }

    cols.push({
      id: 'createdAt',
      accessorKey: 'createdAt',
      header: t('web.violations.createdAt'),
      meta: { label: t('web.violations.createdAt') },
      cell: ({ row }) => <DateText value={row.original.createdAt} format="datetime" />,
    });

    return cols;
  }, [canSeeMoney, t]);

  return (
    <div className="space-y-md">
      <PageHeader
        title={t('shared.violations_title')}
        subtitle={t('web.violations.subtitle')}
        actions={
          <Can perm={P.violationsCreate}>
            <Link
              href="/violations/new"
              className="inline-flex h-8 items-center justify-center rounded-lg bg-primary px-sm t-label text-primary-foreground hover:opacity-90"
            >
              {t('shared.violation_raise')}
            </Link>
          </Can>
        }
      />

      <FilterBar state={filters} onChange={setFilters} onReset={reset} storageKey="violations.views">
        <SelectFilter
          name="status"
          label={t('web.violations.status')}
          options={statusOptions}
          multiple
        />
        <SelectFilter
          name="severity"
          label={t('web.violations.severity')}
          options={severityOptions}
          multiple
        />
        <LookupFilter
          name="typeId"
          label={t('web.violations.type')}
          endpoint={endpoints.lookups.violationTypes}
        />
        <LookupFilter
          name="userId"
          label={t('web.violations.subject')}
          endpoint={endpoints.users.list}
          mapOption={(item) => ({
            value: String(item.id ?? ''),
            label: String(item.fullName ?? item.name ?? item.id ?? ''),
          })}
        />
        <DateRangeFilter from="dateFrom" to="dateTo" label={t('web.violations.dateRange')} />
        <BooleanFilter name="autoGenerated" label={t('shared.violations_filter_auto_only')} />
        <BranchFilter readAllPerm={P.violationsReadAll} />
      </FilterBar>

      <DataTable
        columns={columns}
        data={query.data?.data ?? []}
        meta={query.data?.meta}
        state={filters}
        onStateChange={setFilters}
        sortableColumns={['createdAt', 'severity', 'status']}
        isLoading={query.isLoading}
        isFetching={query.isFetching && !query.isLoading}
        error={query.error}
        onRetry={() => void query.refetch()}
        emptyState={
          <EmptyState
            filtered={hasActiveFilters}
            title={
              hasActiveFilters
                ? t('web.filters.filteredEmptyTitle')
                : t('shared.violations_empty_title')
            }
            description={
              hasActiveFilters
                ? t('web.filters.filteredEmptyBody')
                : t('shared.violations_empty_subtitle')
            }
          />
        }
        rowHref={(row) => `/violations/${row.id}`}
        columnVisibility={{ storageKey: 'violations.columns' }}
        density
        sticky={{ header: true, firstColumn: true }}
        selection={{ enabled: false }}
      />
    </div>
  );
}
