import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:machinery/core/lookups/lookup_entity.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/data/models/violation_response_model.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';
import 'package:machinery/feature/violations/domain/params/violation_action_params.dart';
import 'package:machinery/feature/violations/domain/params/violations_query_params.dart';

/// Payloads copied verbatim from the running API after driving a violation
/// through its whole life: raised, acknowledged, then charged.
///
/// The row shape never changes between those states — only the timestamps and
/// `status` fill in — so the states are pinned individually to catch a parser
/// that reads `chargedAt` but forgets `resolvedAt`, or that assumes a machine
/// is always attached.
void main() {
  Map<String, dynamic> decode(String body) =>
      jsonDecode(body) as Map<String, dynamic>;

  const String openViolation = '''
{
  "id": "cfe80069-fcbf-4bd2-bb0e-bb42daef99c5",
  "type": {
    "id": "a35e63aa-2e4d-453b-935a-19ca7a311798",
    "code": "BATTERY_MISMATCH",
    "name": "بطارية غير مطابقة",
    "defaultSeverity": "HIGH"
  },
  "user": { "id": "79caacfe-5cb9-4afc-af58-b4b797a696b5", "fullName": "مدير التطوير" },
  "machine": null,
  "transferId": null,
  "severity": "MEDIUM",
  "status": "OPEN",
  "description": "تأخير في تسليم الماكينة",
  "chargedAmount": null,
  "chargedAt": null,
  "waiverReason": null,
  "acknowledgedAt": null,
  "resolvedAt": null,
  "autoGenerated": false,
  "isEditable": true,
  "createdAt": "2026-09-08T06:50:37.575Z"
}
''';

  group('violations', () {
    test('a freshly raised violation parses with every outcome field null', () {
      final ViolationEntity violation = ViolationResponseModel.fromJson(
        decode(openViolation),
      ).toEntity();

      expect(violation.status, ViolationStatus.open);
      expect(violation.description, 'تأخير في تسليم الماكينة');
      expect(violation.type.code, 'BATTERY_MISMATCH');
      expect(violation.type.name, 'بطارية غير مطابقة');
      expect(violation.user.fullName, 'مدير التطوير');

      // The manual severity overrides the type's default — the reviewer judged
      // this one milder than a battery mismatch usually is.
      expect(violation.type.defaultSeverity, ViolationSeverity.high);
      expect(violation.severity, ViolationSeverity.medium);

      expect(violation.machine, isNull);
      expect(violation.transferId, isNull);
      expect(violation.chargedAmount, isNull);
      expect(violation.chargedAt, isNull);
      expect(violation.acknowledgedAt, isNull);
      expect(violation.resolvedAt, isNull);
      expect(violation.autoGenerated, isFalse);
      expect(violation.isEditable, isTrue);
    });

    test('acknowledging stamps a time without resolving the row', () {
      final ViolationEntity violation = ViolationResponseModel.fromJson(
        decode(
          openViolation
              .replaceFirst('"status": "OPEN"', '"status": "ACKNOWLEDGED"')
              .replaceFirst(
                '"acknowledgedAt": null',
                '"acknowledgedAt": "2026-09-08T06:50:37.640Z"',
              ),
        ),
      ).toEntity();

      expect(violation.status, ViolationStatus.acknowledged);
      expect(violation.acknowledgedAt, isNotNull);
      expect(violation.resolvedAt, isNull);
      expect(violation.chargedAmount, isNull);
    });

    test('charging fills the amount, the charge time and the resolution', () {
      final ViolationEntity violation = ViolationResponseModel.fromJson(
        decode('''
{
  "id": "209da0c2-bb54-4258-bbf0-6412c1644494",
  "type": {
    "id": "a35e63aa-2e4d-453b-935a-19ca7a311798",
    "code": "BATTERY_MISMATCH",
    "name": "بطارية غير مطابقة",
    "defaultSeverity": "HIGH"
  },
  "user": { "id": "79caacfe-5cb9-4afc-af58-b4b797a696b5", "fullName": "مدير التطوير" },
  "machine": { "id": "b52723ff-3efe-454e-bf16-62af2ee9f74a", "serial": "SN-1009" },
  "transferId": "6c1f0f7e-2a55-4a6b-9b1c-9f2a1d3e4f50",
  "severity": "MEDIUM",
  "status": "CHARGED",
  "description": "تأخير في تسليم الماكينة",
  "chargedAmount": 150,
  "chargedAt": "2026-09-08T06:51:15.202Z",
  "waiverReason": null,
  "acknowledgedAt": "2026-09-08T06:51:15.362Z",
  "resolvedAt": "2026-09-08T06:51:15.375Z",
  "autoGenerated": true,
  "isEditable": false,
  "createdAt": "2026-09-08T06:51:15.296Z"
}
'''),
      ).toEntity();

      expect(violation.status, ViolationStatus.charged);
      expect(violation.chargedAmount, 150);
      expect(violation.chargedAt, isNotNull);
      expect(violation.resolvedAt, isNotNull);
      expect(violation.machine?.serial, 'SN-1009');
      expect(violation.transferId, isNotNull);

      // A row the return-leg detector raised is read-only; the detail screen
      // hides its edit action off this flag alone.
      expect(violation.autoGenerated, isTrue);
      expect(violation.isEditable, isFalse);
    });

    test('a waived violation carries a reason instead of an amount', () {
      final ViolationEntity violation = ViolationResponseModel.fromJson(
        decode(
          openViolation
              .replaceFirst('"status": "OPEN"', '"status": "WAIVED"')
              .replaceFirst(
                '"waiverReason": null',
                '"waiverReason": "خطأ في التسجيل"',
              )
              .replaceFirst(
                '"resolvedAt": null',
                '"resolvedAt": "2026-09-08T07:00:00.000Z"',
              ),
        ),
      ).toEntity();

      expect(violation.status, ViolationStatus.waived);
      expect(violation.waiverReason, 'خطأ في التسجيل');
      expect(violation.chargedAmount, isNull);
      expect(violation.resolvedAt, isNotNull);
    });
  });

  group('violation summary', () {
    test('an unblemished record parses as zeroes across every bucket', () {
      final ViolationSummary summary = ViolationSummaryModel.fromJson(
        decode('''
{
  "user": { "id": "79caacfe-5cb9-4afc-af58-b4b797a696b5", "fullName": "مدير التطوير" },
  "branch": null,
  "totals": { "all": 0, "open": 0, "charged": 0, "waived": 0 },
  "byType": [],
  "bySeverity": { "HIGH": 0, "MEDIUM": 0, "LOW": 0 },
  "totalCharged": 0,
  "last12Months": [
    { "month": "2025-10", "count": 0 }, { "month": "2025-11", "count": 0 },
    { "month": "2025-12", "count": 0 }, { "month": "2026-01", "count": 0 },
    { "month": "2026-02", "count": 0 }, { "month": "2026-03", "count": 0 },
    { "month": "2026-04", "count": 0 }, { "month": "2026-05", "count": 0 },
    { "month": "2026-06", "count": 0 }, { "month": "2026-07", "count": 0 },
    { "month": "2026-08", "count": 0 }, { "month": "2026-09", "count": 0 }
  ],
  "trend": "STEADY"
}
'''),
      ).toEntity();

      expect(summary.user.fullName, 'مدير التطوير');
      expect(summary.branch, isNull);
      expect(summary.totals.all, 0);
      expect(summary.totalCharged, 0);
      expect(summary.byType, isEmpty);
      expect(summary.trend, ViolationTrend.steady);

      // The window is always twelve months, back-filled with zeroes, so the
      // chart never has to reason about gaps.
      expect(summary.last12Months, hasLength(12));
      expect(summary.last12Months.first.month, '2025-10');
      expect(summary.last12Months.last.month, '2026-09');
    });

    test('a marked record parses its per-type and per-severity breakdown', () {
      final ViolationSummary summary = ViolationSummaryModel.fromJson(
        decode('''
{
  "user": { "id": "79caacfe-5cb9-4afc-af58-b4b797a696b5", "fullName": "أحمد مندوب" },
  "branch": "فرع القاهرة",
  "totals": { "all": 5, "open": 2, "charged": 2, "waived": 1 },
  "byType": [
    { "code": "BATTERY_MISMATCH", "name": "بطارية غير مطابقة", "count": 3, "chargedAmount": 450 },
    { "code": "MISSING_CHARGER", "name": "شاحن مفقود", "count": 2, "chargedAmount": 0 }
  ],
  "bySeverity": { "HIGH": 3, "MEDIUM": 1, "LOW": 1 },
  "totalCharged": 450,
  "last12Months": [{ "month": "2026-09", "count": 5 }],
  "trend": "WORSENING"
}
'''),
      ).toEntity();

      // The summary names the branch rather than nesting a reference object,
      // so there is no id to navigate from here.
      expect(summary.branch, 'فرع القاهرة');
      expect(summary.totals.all, 5);
      expect(summary.totals.open, 2);
      expect(summary.totals.charged, 2);
      expect(summary.totals.waived, 1);
      expect(summary.totalCharged, 450);
      expect(summary.trend, ViolationTrend.worsening);

      // Types are grouped by code and returned heaviest-first.
      expect(summary.byType, hasLength(2));
      expect(summary.byType.first.code, 'BATTERY_MISMATCH');
      expect(summary.byType.first.name, 'بطارية غير مطابقة');
      expect(summary.byType.first.count, 3);
      expect(summary.byType.first.chargedAmount, 450);
      expect(summary.byType.last.chargedAmount, 0);

      expect(summary.bySeverity[ViolationSeverity.high], 3);
      expect(summary.bySeverity[ViolationSeverity.medium], 1);
      expect(summary.bySeverity[ViolationSeverity.low], 1);
    });
  });

  group('lookups', () {
    test('a violation type carries the severity the detector will apply', () {
      final ViolationTypeEntity type = ViolationTypeEntity.fromJson(
        decode('''
{
  "id": "a35e63aa-2e4d-453b-935a-19ca7a311798",
  "code": "BATTERY_MISMATCH",
  "name": "بطارية غير مطابقة",
  "isActive": true,
  "sortOrder": 10,
  "description": "رقم البطارية المستلمة لا يطابق البطارية المرتبطة بالماكينة",
  "defaultSeverity": "HIGH"
}
'''),
      );

      expect(type.code, 'BATTERY_MISMATCH');
      expect(type.defaultSeverity, ViolationSeverity.high);
      expect(type.isActive, isTrue);
    });

    test('a payment method parses without the violation-only fields', () {
      final LookupEntity method = LookupEntity.fromJson(
        decode(
          '{"id":"cfe51c79","code":"CASH","name":"نقدي","isActive":true,"sortOrder":10}',
        ),
      );

      expect(method.code, 'CASH');
      expect(method.name, 'نقدي');
      expect(method.isActive, isTrue);
    });
  });

  group('violation request params', () {
    test('filters serialise as repeated enum values, not a joined string', () {
      final Map<String, dynamic> query = const ViolationsQueryParams(
        statuses: <ViolationStatus>[
          ViolationStatus.open,
          ViolationStatus.acknowledged,
        ],
        severities: <ViolationSeverity>[ViolationSeverity.high],
        autoGeneratedOnly: true,
      ).toQuery();

      expect(query['status'], <String>['OPEN', 'ACKNOWLEDGED']);
      expect(query['severity'], <String>['HIGH']);
      expect(query['autoGenerated'], true);
    });

    test('an unfiltered query sends nothing but the page window', () {
      final Map<String, dynamic> query = const ViolationsQueryParams()
          .toQuery();

      expect(query.keys, containsAll(<String>['page', 'limit']));
      expect(query.containsKey('status'), isFalse);
      expect(query.containsKey('severity'), isFalse);
      expect(query.containsKey('autoGenerated'), isFalse);
    });

    test('create sends violationTypeId, the name the backend validates', () {
      final Map<String, dynamic> body = const CreateViolationParams(
        violationTypeId: 'a35e63aa-2e4d-453b-935a-19ca7a311798',
        userId: '79caacfe-5cb9-4afc-af58-b4b797a696b5',
        severity: ViolationSeverity.medium,
        description: '  تأخير في تسليم الماكينة  ',
      ).toJson();

      // The DTO rejects `typeId` outright, so the key name is load-bearing.
      expect(body['violationTypeId'], 'a35e63aa-2e4d-453b-935a-19ca7a311798');
      expect(body.containsKey('typeId'), isFalse);
      expect(body['severity'], 'MEDIUM');
      expect(body['description'], 'تأخير في تسليم الماكينة');
      expect(body.containsKey('machineId'), isFalse);
    });

    test('charge sends the ISO timestamp the backend requires', () {
      final Map<String, dynamic> body = const ChargeViolationParams(
        amount: 150,
        paymentMethodId: 'cfe51c79-b724-46c7-977f-c51c7ce78bc5',
        chargedAt: '2026-09-08T06:51:15.202Z',
      ).toJson();

      expect(body['amount'], 150);
      expect(body['chargedAt'], '2026-09-08T06:51:15.202Z');
      expect(body.containsKey('notes'), isFalse);
    });
  });
}
