import 'package:dartz/dartz.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:machinery/core/network_services/api_service_failure.dart';
import 'package:machinery/core/services/finance_change_notifier.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/data/logic/violation_detail/violation_detail_cubit.dart';
import 'package:machinery/feature/violations/data/logic/violation_detail/violation_detail_state.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';
import 'package:machinery/feature/violations/domain/params/violation_action_params.dart';
import 'package:machinery/feature/violations/domain/repos/violations_repo.dart';

const ViolationTypeRef _type = ViolationTypeRef(
  id: 't1',
  code: 'MISSING_CHARGER',
  name: 'Missing charger',
  defaultSeverity: ViolationSeverity.medium,
);
const ViolationUserRef _user = ViolationUserRef(id: 'u1', fullName: 'Ahmed');

const ViolationEntity _open = ViolationEntity(
  id: 'v1',
  type: _type,
  user: _user,
  severity: ViolationSeverity.medium,
  status: ViolationStatus.open,
  description: 'No charger came back with it.',
  autoGenerated: false,
  isEditable: true,
);

class _FakeViolationsRepo implements ViolationsRepo {
  Either<ServerFailure, ViolationEntity>? actionResult;
  String? lastActedId;

  @override
  Future<Either<ServerFailure, ViolationEntity>> fetchViolation({
    required String id,
  }) async {
    lastActedId = id;
    return actionResult ?? const Right(_open);
  }

  @override
  Future<Either<ServerFailure, ViolationEntity>> acknowledge({
    required String id,
  }) async {
    lastActedId = id;
    return actionResult ?? Left(ServerFailure(''));
  }

  @override
  Future<Either<ServerFailure, ViolationEntity>> charge({
    required String id,
    required ChargeViolationParams params,
  }) async {
    lastActedId = id;
    return actionResult ?? Left(ServerFailure(''));
  }

  @override
  Future<Either<ServerFailure, ViolationEntity>> waive({
    required String id,
    required WaiveViolationParams params,
  }) async {
    lastActedId = id;
    return actionResult ?? Left(ServerFailure(''));
  }

  @override
  Future<Either<ServerFailure, ViolationEntity>> updateViolation({
    required String id,
    required UpdateViolationParams params,
  }) async {
    lastActedId = id;
    return actionResult ?? Left(ServerFailure(''));
  }

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnimplementedError(invocation.memberName.toString());
}

void main() {
  test(
    'acknowledge() moves the row forward and clears actionInProgress',
    () async {
      final _FakeViolationsRepo repo = _FakeViolationsRepo()
        ..actionResult = const Right(
          ViolationEntity(
            id: 'v1',
            type: _type,
            user: _user,
            severity: ViolationSeverity.medium,
            status: ViolationStatus.acknowledged,
            description: 'No charger came back with it.',
            autoGenerated: false,
            isEditable: true,
          ),
        );

      final ViolationDetailCubit cubit = ViolationDetailCubit(
        violationsRepo: repo,
        violationId: 'v1',
        financeChangeNotifier: FinanceChangeNotifier(),
        initial: _open,
      );

      await cubit.acknowledge();

      final ViolationDetailLoaded state = cubit.state as ViolationDetailLoaded;
      expect(state.violation.status, ViolationStatus.acknowledged);
      expect(state.actionInProgress, isFalse);
      expect(cubit.lastOutcome, ViolationActionOutcome.acknowledged);

      await cubit.close();
    },
  );

  test(
    'a failed action surfaces lastError and leaves the row untouched',
    () async {
      final _FakeViolationsRepo repo = _FakeViolationsRepo()
        ..actionResult = Left(ServerFailure('cannot acknowledge'));

      final ViolationDetailCubit cubit = ViolationDetailCubit(
        violationsRepo: repo,
        violationId: 'v1',
        financeChangeNotifier: FinanceChangeNotifier(),
        initial: _open,
      );

      await cubit.acknowledge();

      expect(cubit.lastError, 'cannot acknowledge');
      expect(cubit.lastOutcome, isNull);
      final ViolationDetailLoaded state = cubit.state as ViolationDetailLoaded;
      expect(state.violation.status, ViolationStatus.open);

      await cubit.close();
    },
  );

  test('charge() notifies FinanceChangeNotifier, waive() does not', () async {
    final FinanceChangeNotifier notifier = FinanceChangeNotifier();
    final List<void> events = <void>[];
    final subscription = notifier.onChange.listen(events.add);

    final _FakeViolationsRepo repo = _FakeViolationsRepo()
      ..actionResult = const Right(
        ViolationEntity(
          id: 'v1',
          type: _type,
          user: _user,
          severity: ViolationSeverity.medium,
          status: ViolationStatus.charged,
          description: 'No charger came back with it.',
          autoGenerated: false,
          isEditable: true,
          chargedAmount: 50,
        ),
      );

    final ViolationDetailCubit chargeCubit = ViolationDetailCubit(
      violationsRepo: repo,
      violationId: 'v1',
      financeChangeNotifier: notifier,
      initial: _open,
    );

    await chargeCubit.charge(
      const ChargeViolationParams(
        amount: 50,
        paymentMethodId: 'pm1',
        chargedAt: '2026-01-01T00:00:00.000Z',
      ),
    );
    await chargeCubit.close();

    // Let the broadcast stream's microtask deliver before asserting.
    await Future<void>.delayed(Duration.zero);
    expect(events, hasLength(1));

    repo.actionResult = const Right(
      ViolationEntity(
        id: 'v1',
        type: _type,
        user: _user,
        severity: ViolationSeverity.medium,
        status: ViolationStatus.waived,
        description: 'No charger came back with it.',
        autoGenerated: false,
        isEditable: true,
        waiverReason: 'One-off, forgiven.',
      ),
    );
    final ViolationDetailCubit waiveCubit = ViolationDetailCubit(
      violationsRepo: repo,
      violationId: 'v1',
      financeChangeNotifier: notifier,
      initial: _open,
    );
    await waiveCubit.waive(
      const WaiveViolationParams(reason: 'One-off, forgiven.'),
    );
    await waiveCubit.close();
    await Future<void>.delayed(Duration.zero);

    // Still just the one event from the charge above.
    expect(events, hasLength(1));

    await subscription.cancel();
  });

  test('edit() is refused server-side on an auto-generated row, and that '
      'surfaces as lastError rather than a silent no-op', () async {
    const ViolationEntity autoGenerated = ViolationEntity(
      id: 'v2',
      type: _type,
      user: _user,
      severity: ViolationSeverity.high,
      status: ViolationStatus.open,
      description: 'Battery serial did not match.',
      autoGenerated: true,
      isEditable: false,
    );

    final _FakeViolationsRepo repo = _FakeViolationsRepo()
      ..actionResult = Left(ServerFailure('AUTO_VIOLATION_IMMUTABLE'));

    final ViolationDetailCubit cubit = ViolationDetailCubit(
      violationsRepo: repo,
      violationId: 'v2',
      financeChangeNotifier: FinanceChangeNotifier(),
      initial: autoGenerated,
    );

    await cubit.edit(
      const UpdateViolationParams(description: 'Corrected description'),
    );

    expect(cubit.lastError, 'AUTO_VIOLATION_IMMUTABLE');
    expect(cubit.lastOutcome, isNull);

    await cubit.close();
  });
}
