import 'package:dartz/dartz.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:machinery/core/di/service_locator.dart';
import 'package:machinery/core/lookups/lookup_entity.dart';
import 'package:machinery/core/lookups/lookups_repo.dart';
import 'package:machinery/core/network_services/api_service.dart';
import 'package:machinery/core/network_services/api_service_failure.dart';
import 'package:machinery/core/network_services/models/pagination_meta_model.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/data/logic/violations_list/violations_list_cubit.dart';
import 'package:machinery/feature/violations/data/logic/violations_list/violations_list_state.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';
import 'package:machinery/feature/violations/domain/params/violations_query_params.dart';
import 'package:machinery/feature/violations/domain/repos/violations_repo.dart';

/// `ViolationsListCubit.load()` also lazily fetches the violation-type lookup
/// through `getIt<LookupsRepo>()` for the filter sheet — a real network call
/// this suite must not make. `LookupsRepo` is a concrete class, so this
/// subclasses it and overrides the one method under test rather than faking
/// the whole thing; `apiService` is never touched because `violationTypes()`
/// never calls `super`.
class _FakeLookupsRepo extends LookupsRepo {
  _FakeLookupsRepo() : super(apiService: ApiService());

  @override
  Future<Either<ServerFailure, List<LookupEntity>>> violationTypes() async {
    return const Right(<LookupEntity>[]);
  }
}

ViolationEntity _violation(String id) {
  return ViolationEntity(
    id: id,
    type: const ViolationTypeRef(
      id: 't1',
      code: 'MISSING_CHARGER',
      name: 'Missing charger',
      defaultSeverity: ViolationSeverity.medium,
    ),
    user: const ViolationUserRef(id: 'u1', fullName: 'Ahmed'),
    severity: ViolationSeverity.medium,
    status: ViolationStatus.open,
    description: 'No charger came back with it.',
    autoGenerated: true,
    isEditable: false,
  );
}

class _FakeViolationsRepo implements ViolationsRepo {
  Either<ServerFailure, ViolationsPage>? pageResult;
  ViolationsQueryParams? lastParams;
  int fetchCalls = 0;

  @override
  Future<Either<ServerFailure, ViolationsPage>> fetchViolations({
    required ViolationsQueryParams params,
  }) async {
    fetchCalls++;
    lastParams = params;
    return pageResult ?? Left(ServerFailure(''));
  }

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnimplementedError(invocation.memberName.toString());
}

void main() {
  setUp(() {
    getIt.registerLazySingleton<LookupsRepo>(_FakeLookupsRepo.new);
  });

  tearDown(() {
    getIt.unregister<LookupsRepo>();
  });

  test('load() carries the scope it was opened with into the query', () async {
    final _FakeViolationsRepo repo = _FakeViolationsRepo()
      ..pageResult = Right(
        ViolationsPage(
          violations: <ViolationEntity>[_violation('v1')],
          meta: const PaginationMetaModel(
            page: 1,
            limit: 20,
            total: 1,
            totalPages: 1,
            hasNext: false,
          ),
        ),
      );

    final ViolationsListCubit cubit = ViolationsListCubit(violationsRepo: repo);

    await cubit.load(params: const ViolationsQueryParams(userId: 'u1'));

    expect(cubit.state, isA<ViolationsListLoaded>());
    final ViolationsListLoaded state = cubit.state as ViolationsListLoaded;
    expect(state.violations, hasLength(1));
    expect(repo.lastParams?.userId, 'u1');
    // load() always resets to page 1, even if the caller's params carried a
    // stale page number from a previous session.
    expect(repo.lastParams?.page, 1);

    await cubit.close();
  });

  test('a failed load surfaces the offline flag', () async {
    final _FakeViolationsRepo repo = _FakeViolationsRepo()
      ..pageResult = Left(OfflineFailure());

    final ViolationsListCubit cubit = ViolationsListCubit(violationsRepo: repo);

    await cubit.load();

    expect((cubit.state as ViolationsListFailure).isOffline, isTrue);

    await cubit.close();
  });

  test(
    'loadMore() appends without clobbering the pages already on screen',
    () async {
      final _FakeViolationsRepo repo = _FakeViolationsRepo();
      final ViolationsListCubit cubit = ViolationsListCubit(
        violationsRepo: repo,
      );

      repo.pageResult = Right(
        ViolationsPage(
          violations: <ViolationEntity>[_violation('v1')],
          meta: const PaginationMetaModel(
            page: 1,
            limit: 1,
            total: 2,
            totalPages: 2,
            hasNext: true,
          ),
        ),
      );
      await cubit.load();

      repo.pageResult = Right(
        ViolationsPage(
          violations: <ViolationEntity>[_violation('v2')],
          meta: const PaginationMetaModel(
            page: 2,
            limit: 1,
            total: 2,
            totalPages: 2,
            hasNext: false,
          ),
        ),
      );
      await cubit.loadMore();

      final ViolationsListLoaded state = cubit.state as ViolationsListLoaded;
      expect(state.violations.map((ViolationEntity v) => v.id), <String>[
        'v1',
        'v2',
      ]);
      expect(state.hasNext, isFalse);

      await cubit.close();
    },
  );

  test(
    'replaceViolation() swaps one row in place, keeping scroll position',
    () async {
      final _FakeViolationsRepo repo = _FakeViolationsRepo()
        ..pageResult = Right(
          ViolationsPage(
            violations: <ViolationEntity>[_violation('v1'), _violation('v2')],
            meta: const PaginationMetaModel(
              page: 1,
              limit: 20,
              total: 2,
              totalPages: 1,
              hasNext: false,
            ),
          ),
        );

      final ViolationsListCubit cubit = ViolationsListCubit(
        violationsRepo: repo,
      );
      await cubit.load();

      final ViolationEntity charged = ViolationEntity(
        id: 'v1',
        type: _violation('v1').type,
        user: _violation('v1').user,
        severity: ViolationSeverity.medium,
        status: ViolationStatus.charged,
        description: 'No charger came back with it.',
        autoGenerated: true,
        isEditable: false,
        chargedAmount: 50,
      );
      cubit.replaceViolation(charged);

      final ViolationsListLoaded state = cubit.state as ViolationsListLoaded;
      expect(state.violations.first.status, ViolationStatus.charged);
      expect(state.violations.first.chargedAmount, 50);
      expect(state.violations.last.id, 'v2');

      await cubit.close();
    },
  );
}
