import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:machinery/core/di/service_locator.dart';
import 'package:machinery/core/local_storage/local_storage.dart';
import 'package:machinery/core/permissions/permission_keys.dart';
import 'package:machinery/core/permissions/permission_service.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';
import 'package:machinery/feature/violations/presentation/widgets/violation_actions_row.dart';
import 'package:shared_preferences/shared_preferences.dart';

const ViolationTypeRef _type = ViolationTypeRef(
  id: 't1',
  code: 'MISSING_CHARGER',
  name: 'Missing charger',
  defaultSeverity: ViolationSeverity.medium,
);

const ViolationEntity _handRaisedOpen = ViolationEntity(
  id: 'v1',
  type: _type,
  user: ViolationUserRef(id: 'u1', fullName: 'Ahmed'),
  severity: ViolationSeverity.medium,
  status: ViolationStatus.open,
  description: 'Missing charger.',
  autoGenerated: false,
  isEditable: true,
);

const ViolationEntity _autoGeneratedOpen = ViolationEntity(
  id: 'v2',
  type: _type,
  user: ViolationUserRef(id: 'u1', fullName: 'Ahmed'),
  severity: ViolationSeverity.high,
  status: ViolationStatus.open,
  description: 'Battery mismatch.',
  autoGenerated: true,
  isEditable: false,
);

/// `ViolationActionsRow` reads `getIt<PermissionService>()` directly through
/// `PermissionGate`, so this is the smallest DI surface its gating needs — no
/// cubit, no repo, just the one service the widget actually depends on.
Future<void> _withPermissions(List<String> granted) async {
  SharedPreferences.setMockInitialValues(<String, Object>{});
  LocalStorage.local = await SharedPreferences.getInstance();
  final PermissionService service = PermissionService();
  await service.update(granted);

  if (getIt.isRegistered<PermissionService>()) {
    getIt.unregister<PermissionService>();
  }
  getIt.registerSingleton<PermissionService>(service);
}

Widget _wrap(Widget child) {
  return MaterialApp(home: Scaffold(body: child));
}

void main() {
  tearDown(() {
    if (getIt.isRegistered<PermissionService>()) {
      getIt.unregister<PermissionService>();
    }
  });

  testWidgets(
    'acknowledge shows only for the person the violation is against',
    (tester) async {
      await _withPermissions(<String>[]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _handRaisedOpen,
            isBusy: false,
            currentUserId: 'u1',
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(OutlinedButton, Icons.visibility_outlined),
        findsOneWidget,
      );
    },
  );

  testWidgets(
    'acknowledge is hidden for anyone other than the subject, even a supervisor',
    (tester) async {
      await _withPermissions(<String>[P.violationsResolve, P.financeCreate]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _handRaisedOpen,
            isBusy: false,
            currentUserId: 'someone-else',
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(OutlinedButton, Icons.visibility_outlined),
        findsNothing,
      );
    },
  );

  testWidgets(
    'charge needs both violations.resolve and finance.create — neither alone is enough',
    (tester) async {
      await _withPermissions(<String>[P.violationsResolve]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _handRaisedOpen,
            isBusy: false,
            currentUserId: null,
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(FilledButton, Icons.payments_outlined),
        findsNothing,
      );
    },
  );

  testWidgets(
    'charge shows once both violations.resolve and finance.create are granted',
    (tester) async {
      await _withPermissions(<String>[P.violationsResolve, P.financeCreate]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _handRaisedOpen,
            isBusy: false,
            currentUserId: null,
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(FilledButton, Icons.payments_outlined),
        findsOneWidget,
      );
    },
  );

  testWidgets('waive is gated on violations.waive alone', (tester) async {
    await _withPermissions(<String>[P.violationsWaive]);

    await tester.pumpWidget(
      _wrap(
        ViolationActionsRow(
          violation: _handRaisedOpen,
          isBusy: false,
          currentUserId: null,
          onAcknowledge: () {},
          onCharge: () {},
          onWaive: () {},
          onEdit: () {},
        ),
      ),
    );

    expect(
      find.widgetWithIcon(OutlinedButton, Icons.do_not_disturb_on_outlined),
      findsOneWidget,
    );
  });

  testWidgets(
    'edit is hidden on an auto-generated row even with violations.resolve',
    (tester) async {
      await _withPermissions(<String>[P.violationsResolve, P.financeCreate]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _autoGeneratedOpen,
            isBusy: false,
            currentUserId: null,
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(OutlinedButton, Icons.edit_outlined),
        findsNothing,
      );
    },
  );

  testWidgets(
    'edit shows on a hand-raised row once violations.resolve is granted',
    (tester) async {
      await _withPermissions(<String>[P.violationsResolve]);

      await tester.pumpWidget(
        _wrap(
          ViolationActionsRow(
            violation: _handRaisedOpen,
            isBusy: false,
            currentUserId: null,
            onAcknowledge: () {},
            onCharge: () {},
            onWaive: () {},
            onEdit: () {},
          ),
        ),
      );

      expect(
        find.widgetWithIcon(OutlinedButton, Icons.edit_outlined),
        findsOneWidget,
      );
    },
  );

  testWidgets('tapping charge calls its callback', (tester) async {
    await _withPermissions(<String>[P.violationsResolve, P.financeCreate]);
    int taps = 0;

    await tester.pumpWidget(
      _wrap(
        ViolationActionsRow(
          violation: _handRaisedOpen,
          isBusy: false,
          currentUserId: null,
          onAcknowledge: () {},
          onCharge: () => taps++,
          onWaive: () {},
          onEdit: () {},
        ),
      ),
    );

    await tester.tap(
      find.widgetWithIcon(FilledButton, Icons.payments_outlined),
    );
    await tester.pump();

    expect(taps, 1);
  });
}
