import 'package:dartz/dartz.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:machinery/core/lookups/lookup_entity.dart';
import 'package:machinery/core/network_services/api_service_failure.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/users/domain/entities/user_entity.dart';
import 'package:machinery/feature/violations/data/logic/violation_create/violation_create_cubit.dart';
import 'package:machinery/feature/violations/data/logic/violation_create/violation_create_state.dart';
import 'package:machinery/feature/violations/domain/entities/violation_entity.dart';
import 'package:machinery/feature/violations/domain/params/violation_action_params.dart';
import 'package:machinery/feature/violations/domain/repos/violations_repo.dart';

const ViolationTypeEntity _highSeverityType = ViolationTypeEntity(
  id: 't1',
  code: 'BATTERY_MISMATCH',
  name: 'Battery mismatch',
  defaultSeverity: ViolationSeverity.high,
);

const UserEntity _user = UserEntity(
  id: 'u1',
  fullName: 'Ahmed',
  phone: '01000000001',
  roleId: 'r1',
  roleCode: 'REPRESENTATIVE',
  roleName: 'Representative',
  isActive: true,
  mustChangePassword: false,
);

class _FakeViolationsRepo implements ViolationsRepo {
  Either<ServerFailure, ViolationEntity>? createResult;
  CreateViolationParams? lastParams;

  @override
  Future<Either<ServerFailure, ViolationEntity>> createViolation({
    required CreateViolationParams params,
  }) async {
    lastParams = params;
    return createResult ?? Left(ServerFailure(''));
  }

  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw UnimplementedError(invocation.memberName.toString());
}

void main() {
  test('selectType() defaults severity to the type\'s own default', () async {
    final ViolationCreateCubit cubit = ViolationCreateCubit(
      violationsRepo: _FakeViolationsRepo(),
    );

    // Bypass load()'s network call — the cubit only needs a Ready state with
    // the one type on offer.
    cubit.emit(
      const ViolationCreateReady(types: <LookupEntity>[_highSeverityType]),
    );

    cubit.selectType('t1');

    final ViolationCreateReady state = cubit.state as ViolationCreateReady;
    expect(state.typeId, 't1');
    expect(state.severity, ViolationSeverity.high);

    await cubit.close();
  });

  test('selectSeverity() can override the type default', () async {
    final ViolationCreateCubit cubit = ViolationCreateCubit(
      violationsRepo: _FakeViolationsRepo(),
    );

    cubit.emit(
      const ViolationCreateReady(types: <LookupEntity>[_highSeverityType]),
    );
    cubit.selectType('t1');
    cubit.selectSeverity(ViolationSeverity.low);

    expect(
      (cubit.state as ViolationCreateReady).severity,
      ViolationSeverity.low,
    );

    await cubit.close();
  });

  test('submit() is refused without a type, severity, or user', () async {
    final _FakeViolationsRepo repo = _FakeViolationsRepo();
    final ViolationCreateCubit cubit = ViolationCreateCubit(
      violationsRepo: repo,
    );

    cubit.emit(const ViolationCreateReady(types: <LookupEntity>[]));

    await cubit.submit(description: 'Missing charger on return.');

    expect(repo.lastParams, isNull);
    expect(cubit.state, isA<ViolationCreateReady>());

    await cubit.close();
  });

  test('submit() posts the machine id only when one was picked', () async {
    final _FakeViolationsRepo repo = _FakeViolationsRepo()
      ..createResult = const Right(
        ViolationEntity(
          id: 'v1',
          type: ViolationTypeRef(
            id: 't1',
            code: 'BATTERY_MISMATCH',
            name: 'Battery mismatch',
            defaultSeverity: ViolationSeverity.high,
          ),
          user: ViolationUserRef(id: 'u1', fullName: 'Ahmed'),
          severity: ViolationSeverity.high,
          status: ViolationStatus.open,
          description: 'Missing charger on return.',
          autoGenerated: false,
          isEditable: true,
        ),
      );

    final ViolationCreateCubit cubit = ViolationCreateCubit(
      violationsRepo: repo,
    );

    cubit.emit(
      const ViolationCreateReady(
        types: <LookupEntity>[_highSeverityType],
        typeId: 't1',
        severity: ViolationSeverity.high,
        user: _user,
      ),
    );

    await cubit.submit(description: 'Missing charger on return.');

    expect(repo.lastParams?.userId, 'u1');
    expect(repo.lastParams?.violationTypeId, 't1');
    expect(repo.lastParams?.machineId, isNull);
    expect(cubit.state, isA<ViolationCreateSubmitted>());

    await cubit.close();
  });

  test(
    'a failed submit surfaces the error and returns to a re-submittable form',
    () async {
      final _FakeViolationsRepo repo = _FakeViolationsRepo()
        ..createResult = Left(ServerFailure('validation failed'));

      final ViolationCreateCubit cubit = ViolationCreateCubit(
        violationsRepo: repo,
      );

      cubit.emit(
        const ViolationCreateReady(
          types: <LookupEntity>[_highSeverityType],
          typeId: 't1',
          severity: ViolationSeverity.high,
          user: _user,
        ),
      );

      final List<ViolationCreateState> states = <ViolationCreateState>[];
      final subscription = cubit.stream.listen(states.add);

      await cubit.submit(description: 'Missing charger on return.');
      await Future<void>.delayed(Duration.zero);

      final ViolationCreateSubmitFailure failure = states
          .whereType<ViolationCreateSubmitFailure>()
          .single;
      expect(failure.errorMessage, 'validation failed');
      expect(cubit.state, isA<ViolationCreateReady>());
      expect((cubit.state as ViolationCreateReady).isSubmitting, isFalse);

      await subscription.cancel();
      await cubit.close();
    },
  );
}
