import { api } from '@/lib/api/client';
import { endpoints } from '@/lib/api/endpoints';
import type { ListMeta } from '@/lib/api/pagination';

import type {
  ChargeViolationBody,
  CreateViolationBody,
  LookupRow,
  UpdateViolationBody,
  Violation,
  ViolationSummary,
  ViolationType,
  WaiveViolationBody,
} from '../model/types';

export type ViolationsListParams = {
  page?: number;
  limit?: number;
  sortDir?: 'asc' | 'desc';
  sortBy?: 'createdAt' | 'severity' | 'status' | string;
  userId?: string;
  machineId?: string;
  typeId?: string;
  branchId?: string;
  severity?: string | string[];
  status?: string | string[];
  dateFrom?: string;
  dateTo?: string;
  autoGenerated?: boolean;
};

export const violationsApi = {
  list(params?: ViolationsListParams) {
    return api.get<Violation[], ListMeta>(endpoints.violations.list, params);
  },

  detail(id: string) {
    return api.get<Violation>(endpoints.violations.byId(id));
  },

  create(body: CreateViolationBody, idempotencyKey: string) {
    return api.post<Violation>(endpoints.violations.list, body, idempotencyKey);
  },

  update(id: string, body: UpdateViolationBody, idempotencyKey: string) {
    return api.patch<Violation>(endpoints.violations.byId(id), body, idempotencyKey);
  },

  acknowledge(id: string, idempotencyKey: string) {
    return api.post<Violation>(endpoints.violations.acknowledge(id), {}, idempotencyKey);
  },

  charge(id: string, body: ChargeViolationBody, idempotencyKey: string) {
    return api.post<Violation>(endpoints.violations.charge(id), body, idempotencyKey);
  },

  waive(id: string, body: WaiveViolationBody, idempotencyKey: string) {
    return api.post<Violation>(endpoints.violations.waive(id), body, idempotencyKey);
  },

  types(params?: { search?: string; limit?: number; isActive?: boolean }) {
    return api.get<ViolationType[], ListMeta>(endpoints.lookups.violationTypes, {
      search: params?.search,
      limit: params?.limit ?? 100,
      isActive: params?.isActive,
    });
  },

  paymentMethods(params?: { search?: string; limit?: number; isActive?: boolean }) {
    return api.get<LookupRow[], ListMeta>(endpoints.lookups.paymentMethods, {
      search: params?.search,
      limit: params?.limit ?? 50,
      isActive: params?.isActive ?? true,
    });
  },

  forUser(userId: string, params?: ViolationsListParams) {
    return api.get<Violation[], ListMeta>(endpoints.users.violations(userId), params);
  },

  summaryForUser(userId: string) {
    return api.get<ViolationSummary>(endpoints.users.violationsSummary(userId));
  },
};
