import { randomUUID } from 'node:crypto';
import type { App } from 'supertest/types';
import { INestApplication } from '@nestjs/common';
import { MachineStatus } from 'src/common/enums/machine-status.enum';
import { FinanceKind, TransactionSource } from 'src/common/enums/finance.enum';
import {
  MaintenanceResult,
  MaintenanceStatus,
  ResponsibleParty,
  Severity,
  WarehouseType,
} from 'src/common/enums/operations.enum';
import { SignatureMethod, TransferType } from 'src/common/enums/transfer.enum';
import { SystemRole } from 'src/modules/roles/entities/role.entity';
import { Api, fails, ok, okPage } from './utils/api-client';
import {
  createBranch,
  createMerchant,
  loginAsDirector,
  provisionUser,
  ProvisionedUser,
  roleIdByCode,
  uniqueCode,
} from './utils/fixtures';
import { createTestApp } from './utils/test-app';

interface MachineResponse {
  id: string;
  serial: string;
  status: MachineStatus;
  hasBox: boolean;
  purchase: { price: number | null; date: string | null; invoiceNo: string | null };
  maintenance: { repairCount: number; totalRepairCost: number; costVsPricePercent: number | null };
  warranty: { start: string | null; end: string | null };
  battery: { id: string; serial: string } | null;
  branch: { id: string; name: string } | null;
  holder: { type: string; id: string | null } | null;
  decommissionedAt: string | null;
  replacesMachineId: string | null;
  replacedByMachineId: string | null;
}

interface MaintenanceOrderResponse {
  id: string;
  referenceNo: string;
  machine: { id: string; serial: string; status: string };
  location: { id: string; code: string; name: string };
  status: MaintenanceStatus;
  result: MaintenanceResult | null;
  sentAt: string;
  returnedAt: string | null;
  cost: number | null;
  isFreeUnderWarranty: boolean;
  suggestedFreeUnderWarranty: boolean;
  responsibleParty: ResponsibleParty | null;
  responsibleUserId: string | null;
  responsibleMerchantId: string | null;
  outTransferId: string | null;
  inTransferId: string | null;
  financeTransactionId: string | null;
  violationId: string | null;
  subscriptionId: string | null;
  replacementMachineId: string | null;
  reportedFault: string;
  closedAt: string | null;
  cancelReason: string | null;
  branch: { id: string; name: string } | null;
}

interface MaintenanceHistoryResponse {
  machineId: string;
  serial: string;
  totals: {
    orders: number;
    totalCost: number;
    freeUnderWarranty: number;
    chargedToCompany: number;
    chargedToRepresentative: number;
    chargedToMerchant: number;
    chargedToFactory: number;
  };
  orders: MaintenanceOrderResponse[];
  ordersMeta: { page: number; limit: number; total: number; hasNext: boolean };
}

interface FinanceTransactionResponse {
  id: string;
  kind: FinanceKind;
  amount: number;
  category: { code: string | null; name: string };
  source: TransactionSource;
  sourceRefType: string | null;
  sourceRefId: string | null;
  supplier: { id: string; name: string } | null;
  notes: string | null;
}

interface ViolationResponse {
  id: string;
  severity: Severity;
  status: string;
  chargedAmount: number | null;
  autoGenerated: boolean;
  machine: { id: string; serial: string } | null;
  user: { id: string; fullName: string };
  type: { code: string };
}

interface SubscriptionResponse {
  id: string;
  planType: string;
  amount: number;
  machineId: string | null;
  isActive: boolean;
}

interface ReplacementResponse {
  id: string;
  oldMachine: { id: string; serial: string; status: string };
  newMachine: { id: string; serial: string; status: string };
  maintenanceOrderId: string | null;
  reason: string;
  replacedAt: string;
}

interface ChainResponse {
  requestedMachineId: string;
  chainLength: number;
  chain: {
    position: number;
    id: string;
    serial: string;
    status: MachineStatus;
    activeFrom: string;
    activeTo: string | null;
    repairCount: number;
    repairCost: number;
    isCurrent: boolean;
    replacedReason: string | null;
  }[];
  chainTotals: {
    purchasePrice: number | null;
    cumulativeRepairCost: number;
    cumulativeRepairCount: number;
    costToValueRatio: number | null;
    ageMonths: number;
  };
}

interface CostSummaryResponse {
  purchasePrice: number | null;
  totalRepairCost: number;
  repairCount: number;
  costToValueRatio: number | null;
  chargedToCompany: number;
  chargedToRepresentatives: number;
  chargedToMerchants: number;
  freeUnderWarranty: number;
  isInChain: boolean;
  chainLength: number;
  recommendation: string;
}

interface TimelineEventResponse {
  at: string;
  type: string;
  refId: string;
  refNo: string | null;
  details: Record<string, unknown>;
}

interface LookupResponse {
  id: string;
  code: string;
}

interface WarehouseResponse {
  id: string;
  type: WarehouseType;
  branchId: string | null;
}

interface MachineModelResponse {
  id: string;
  machineType: { id: string; requiresSim: boolean };
}

interface TransferResponse {
  id: string;
  type: TransferType;
  status: string;
  payloadHash: string;
}

interface PaymentMethodResponse {
  id: string;
  code: string;
}

const DRAWN = { method: SignatureMethod.DRAWN_SIGNATURE, deviceModel: 'e2e' };

/** Inside any warranty window a fixture opens, and stable across a run. */
const SENT_AT = '2026-02-14T08:30:00.000Z';
const RETURNED_AT = '2026-03-02T14:00:00.000Z';

describe('Maintenance, replacement and the machine history reads (e2e)', () => {
  let app: INestApplication;
  let server: App;
  let director: Api;

  let branchId: string;
  let supervisor: ProvisionedUser;
  let representative: ProvisionedUser;

  let companyWarehouseId: string;
  let maintenanceWarehouseId: string;
  let posModelId: string;
  let workshopId: string;
  let factoryId: string;
  let paymentMethodId: string;

  beforeAll(async () => {
    ({ app, server } = await createTestApp());
    director = await loginAsDirector(server);

    branchId = (await createBranch(director, 'فرع الصيانة')).id;

    supervisor = await provisionUser(server, director, {
      roleId: await roleIdByCode(director, SystemRole.BRANCH_SUPERVISOR),
      branchId,
      fullName: 'مشرف الصيانة',
    });

    representative = await provisionUser(server, director, {
      roleId: await roleIdByCode(director, SystemRole.REPRESENTATIVE),
      branchId,
      fullName: 'مندوب الصيانة',
    });

    const warehouses = await ok<WarehouseResponse[]>(director.get('/warehouses?limit=100'));
    companyWarehouseId = warehouses.find((row) => row.type === WarehouseType.COMPANY_MAIN)!.id;

    // Nothing seeds a workshop store — the internal-workshop route has nowhere to send a machine
    // until somebody opens one.
    maintenanceWarehouseId = (
      await ok<WarehouseResponse>(
        director.post('/warehouses', { type: WarehouseType.MAINTENANCE, name: 'ورشة الاختبار' }),
        201,
      )
    ).id;

    posModelId = (await ok<MachineModelResponse[]>(director.get('/machine-models?limit=100'))).find(
      (model) => model.machineType.requiresSim,
    )!.id;

    const locations = await ok<LookupResponse[]>(director.get('/maintenance-locations'));
    workshopId = locations.find((row) => row.code === 'INTERNAL_WORKSHOP')!.id;
    factoryId = locations.find((row) => row.code === 'FACTORY')!.id;

    paymentMethodId = (await ok<PaymentMethodResponse[]>(director.get('/payment-methods')))[0].id;
  });

  afterAll(async () => {
    await app.close();
  });

  // ── fixtures ───────────────────────────────────────────────────────────────

  let serialCounter = 0;

  interface MachineOptions {
    purchasePrice?: number | null;
    warrantyEnd?: string | null;
  }

  async function createMachine(options: MachineOptions = {}): Promise<MachineResponse> {
    serialCounter += 1;
    const tag = `${uniqueCode('M')}_${serialCounter}`;
    const price = options.purchasePrice === undefined ? 4200 : options.purchasePrice;

    return ok<MachineResponse>(
      director.post('/machines', {
        serial: `SN-${tag}`,
        machineModelId: posModelId,
        simSerial: `SIM-${tag}`,
        boxSerial: `BX-${tag}`,
        battery: { serial: `BT-${tag}` },
        hasBox: true,
        ...(price === null ? {} : { purchasePrice: price }),
        purchaseDate: '2025-02-10',
        warrantyStart: '2025-02-10',
        ...(options.warrantyEnd === null
          ? {}
          : { warrantyEnd: options.warrantyEnd ?? '2026-12-31' }),
      }),
      201,
    );
  }

  function openOrder(
    machineId: string,
    locationId = workshopId,
    body: Record<string, unknown> = {},
  ): Promise<MaintenanceOrderResponse> {
    return ok<MaintenanceOrderResponse>(
      director.post('/maintenance-orders', {
        machineId,
        locationId,
        reportedFault: 'الشاشة لا تعمل',
        sentAt: SENT_AT,
        ...body,
      }),
      201,
    );
  }

  function sendOrder(id: string): Promise<MaintenanceOrderResponse> {
    return ok<MaintenanceOrderResponse>(
      director.post(`/maintenance-orders/${id}/send`, {
        occurredAt: SENT_AT,
        // Always explicit: a second workshop opened by another spec would make the store
        // ambiguous, and the service refuses to guess.
        warehouseId: maintenanceWarehouseId,
        signature: DRAWN,
      }),
    );
  }

  function receiveOrder(id: string): Promise<MaintenanceOrderResponse> {
    return ok<MaintenanceOrderResponse>(
      director.post(`/maintenance-orders/${id}/receive`, {
        occurredAt: RETURNED_AT,
        warehouseId: companyWarehouseId,
        signature: DRAWN,
      }),
    );
  }

  function closeOrder(
    id: string,
    body: Record<string, unknown> = {},
  ): Promise<MaintenanceOrderResponse> {
    return ok<MaintenanceOrderResponse>(
      director.post(`/maintenance-orders/${id}/close`, {
        result: MaintenanceResult.REPAIRED,
        isFreeUnderWarranty: false,
        cost: 350,
        responsibleParty: ResponsibleParty.COMPANY,
        paymentMethodId,
        returnedAt: RETURNED_AT,
        ...body,
      }),
    );
  }

  /** Opens, sends and receives, leaving the order at `RETURNED` and ready to close. */
  async function returnedOrder(
    machineId: string,
    locationId = workshopId,
  ): Promise<MaintenanceOrderResponse> {
    const order = await openOrder(machineId, locationId);
    await sendOrder(order.id);

    return receiveOrder(order.id);
  }

  function readMachine(id: string): Promise<MachineResponse> {
    return ok<MachineResponse>(director.get(`/machines/${id}`));
  }

  function readOrder(id: string): Promise<MaintenanceOrderResponse> {
    return ok<MaintenanceOrderResponse>(director.get(`/maintenance-orders/${id}`));
  }

  /** Every auto-posted maintenance expense that belongs to one order. */
  async function expensesFor(orderId: string): Promise<FinanceTransactionResponse[]> {
    const { items } = await okPage<FinanceTransactionResponse>(
      director.get(`/finance/transactions?source=${TransactionSource.AUTO_MAINTENANCE}&limit=100`),
    );

    return items.filter((row) => row.sourceRefId === orderId);
  }

  function factorySwap(overrides: Record<string, unknown> = {}): Record<string, unknown> {
    serialCounter += 1;
    const tag = `${uniqueCode('R')}_${serialCounter}`;

    return {
      newSerial: `SN-${tag}`,
      newBattery: { serial: `BT-${tag}` },
      newSimSerial: `SIM-${tag}`,
      newBoxSerial: `BX-${tag}`,
      hasBox: true,
      reason: 'لوحة رئيسية تالفة',
      replacedAt: RETURNED_AT,
      ...overrides,
    };
  }

  // ── the lifecycle ──────────────────────────────────────────────────────────

  describe('the order lifecycle', () => {
    it('walks a machine out to the workshop and back, and bills the company for it', async () => {
      const machine = await createMachine();

      const opened = await openOrder(machine.id);
      expect(opened.referenceNo).toMatch(/^MNT-\d{4}-\d{6}$/);
      expect(opened.status).toBe(MaintenanceStatus.OPEN);
      expect(opened.location.code).toBe('INTERNAL_WORKSHOP');

      const sent = await sendOrder(opened.id);
      expect(sent.status).toBe(MaintenanceStatus.IN_PROGRESS);
      expect(sent.outTransferId).not.toBeNull();
      expect((await readMachine(machine.id)).status).toBe(MachineStatus.UNDER_MAINTENANCE);

      const received = await receiveOrder(opened.id);
      expect(received.status).toBe(MaintenanceStatus.RETURNED);
      expect(received.inTransferId).not.toBeNull();
      expect(received.returnedAt).toBe(RETURNED_AT);
      expect((await readMachine(machine.id)).status).toBe(MachineStatus.IN_COMPANY_WAREHOUSE);

      const closed = await closeOrder(opened.id, { cost: 350, performedByName: 'محمد الفني' });
      expect(closed.status).toBe(MaintenanceStatus.CLOSED);
      expect(closed.result).toBe(MaintenanceResult.REPAIRED);
      expect(closed.cost).toBe(350);
      expect(closed.financeTransactionId).not.toBeNull();

      const after = await readMachine(machine.id);
      expect(after.maintenance.repairCount).toBe(1);
      expect(after.maintenance.totalRepairCost).toBe(350);
    });

    it('sends a machine to the factory without needing a store to point at', async () => {
      const machine = await createMachine();
      const order = await openOrder(machine.id, factoryId);

      await ok<MaintenanceOrderResponse>(
        director.post(`/maintenance-orders/${order.id}/send`, {
          occurredAt: SENT_AT,
          signature: DRAWN,
        }),
      );

      expect((await readMachine(machine.id)).status).toBe(MachineStatus.AT_FACTORY);
    });

    it('pre-computes the warranty suggestion from the day it was sent', async () => {
      const covered = await openOrder((await createMachine()).id);
      expect(covered.suggestedFreeUnderWarranty).toBe(true);

      const expired = await openOrder((await createMachine({ warrantyEnd: '2025-06-30' })).id);
      expect(expired.suggestedFreeUnderWarranty).toBe(false);
    });

    it('refuses a second open order for the same machine', async () => {
      const machine = await createMachine();
      await openOrder(machine.id);

      await fails(
        director.post('/maintenance-orders', {
          machineId: machine.id,
          locationId: workshopId,
          reportedFault: 'عطل آخر تمامًا',
          sentAt: SENT_AT,
        }),
        409,
        'MACHINE_ALREADY_IN_MAINTENANCE',
      );
    });

    it('lets the same machine be sent again once the first order is closed', async () => {
      const machine = await createMachine();
      const first = await returnedOrder(machine.id);
      await closeOrder(first.id, { cost: 100 });

      const second = await returnedOrder(machine.id);
      await closeOrder(second.id, { cost: 250 });

      const after = await readMachine(machine.id);
      expect(after.maintenance.repairCount).toBe(2);
      expect(after.maintenance.totalRepairCost).toBe(350);
    });

    it('refuses an order for a machine that is not in the company warehouse', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);
      await closeOrder(order.id, { cost: 10 });

      // Now with the branch supervisor rather than on the company shelf.
      await ok<TransferResponse>(
        director.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.COMPANY_TO_BRANCH,
          toPartyId: supervisor.id,
          occurredAt: new Date().toISOString(),
          items: [{ machineId: machine.id, hasCharger: true, hasBox: true, condition: 'GOOD' }],
        }),
        201,
      );

      await fails(
        director.post('/maintenance-orders', {
          machineId: machine.id,
          locationId: workshopId,
          reportedFault: 'عطل في المكان الخطأ',
          sentAt: SENT_AT,
        }),
        422,
        'INVALID_MACHINE_STATUS',
      );
    });

    it('refuses to receive an order that was never sent', async () => {
      const order = await openOrder((await createMachine()).id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/receive`, {
          warehouseId: companyWarehouseId,
          signature: DRAWN,
        }),
        422,
        'INVALID_MAINTENANCE_STATUS',
      );
    });

    it('refuses to close an order the machine has not come back from', async () => {
      const order = await openOrder((await createMachine()).id);
      await sendOrder(order.id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/close`, {
          result: MaintenanceResult.REPAIRED,
          isFreeUnderWarranty: true,
          responsibleParty: ResponsibleParty.FACTORY,
          returnedAt: RETURNED_AT,
        }),
        422,
        'INVALID_MAINTENANCE_STATUS',
      );
    });

    it('cancels an order that never went anywhere, with a reason', async () => {
      const machine = await createMachine();
      const order = await openOrder(machine.id);

      const cancelled = await ok<MaintenanceOrderResponse>(
        director.post(`/maintenance-orders/${order.id}/cancel`, {
          reason: 'العطل كان في مصدر الكهرباء',
        }),
      );

      expect(cancelled.status).toBe(MaintenanceStatus.CANCELLED);
      expect(cancelled.cancelReason).toBe('العطل كان في مصدر الكهرباء');
      expect((await readMachine(machine.id)).maintenance.repairCount).toBe(0);

      // Cancelling frees the machine, which is the point of the status.
      await openOrder(machine.id);
    });

    it('refuses to cancel a machine that is still away at the workshop', async () => {
      const order = await openOrder((await createMachine()).id);
      await sendOrder(order.id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/cancel`, { reason: 'تم الإلغاء بالخطأ' }),
        422,
        'INVALID_MAINTENANCE_STATUS',
      );
    });

    it('corrects the fault text while the machine is away and not after it is closed', async () => {
      const order = await openOrder((await createMachine()).id);

      const patched = await ok<MaintenanceOrderResponse>(
        director.patch(`/maintenance-orders/${order.id}`, {
          reportedFault: 'الشاشة تعمل ولكن القارئ لا يقرأ',
        }),
      );
      expect(patched.reportedFault).toBe('الشاشة تعمل ولكن القارئ لا يقرأ');

      await sendOrder(order.id);
      await receiveOrder(order.id);
      await closeOrder(order.id, { cost: 80 });

      await fails(
        director.patch(`/maintenance-orders/${order.id}`, { reportedFault: 'تصحيح متأخر' }),
        422,
        'ORDER_ALREADY_CLOSED',
      );
    });
  });

  // ── the close flow and its money ───────────────────────────────────────────

  describe('closing and who pays', () => {
    it('posts exactly one MAINTENANCE expense when the company pays', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);

      const closed = await closeOrder(order.id, { cost: 350, isFreeUnderWarranty: false });

      const posted = await expensesFor(order.id);
      expect(posted).toHaveLength(1);
      expect(posted[0].id).toBe(closed.financeTransactionId);
      expect(posted[0].kind).toBe(FinanceKind.EXPENSE);
      expect(posted[0].amount).toBe(350);
      expect(posted[0].category.code).toBe('MAINTENANCE');
      expect(posted[0].sourceRefType).toBe('MAINTENANCE_ORDER');
    });

    it('posts nothing for a repair the warranty covered, but still counts the repair', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);

      const closed = await closeOrder(order.id, {
        isFreeUnderWarranty: true,
        cost: 500,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
      });

      expect(closed.isFreeUnderWarranty).toBe(true);
      expect(closed.cost).toBe(0);
      expect(closed.financeTransactionId).toBeNull();
      expect(await expensesFor(order.id)).toHaveLength(0);

      const after = await readMachine(machine.id);
      expect(after.maintenance.repairCount).toBe(1);
      expect(after.maintenance.totalRepairCost).toBe(0);
    });

    it('refuses a second close and does not post a second expense', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);
      await closeOrder(order.id, { cost: 420 });

      await fails(
        director.post(`/maintenance-orders/${order.id}/close`, {
          result: MaintenanceResult.REPAIRED,
          isFreeUnderWarranty: false,
          cost: 420,
          responsibleParty: ResponsibleParty.COMPANY,
          paymentMethodId,
          returnedAt: RETURNED_AT,
        }),
        409,
        'ORDER_ALREADY_CLOSED',
      );

      expect(await expensesFor(order.id)).toHaveLength(1);
      expect((await readMachine(machine.id)).maintenance.repairCount).toBe(1);
    });

    it('raises a violation against the representative who broke it', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);

      const closed = await closeOrder(order.id, {
        cost: 1200,
        responsibleParty: ResponsibleParty.REPRESENTATIVE,
        responsibleUserId: representative.id,
        paymentMethodId: undefined,
      });

      expect(closed.violationId).not.toBeNull();
      expect(closed.financeTransactionId).toBeNull();
      expect(await expensesFor(order.id)).toHaveLength(0);

      const violation = await ok<ViolationResponse>(
        director.get(`/violations/${closed.violationId}`),
      );

      expect(violation.user.id).toBe(representative.id);
      expect(violation.machine?.id).toBe(machine.id);
      expect(violation.chargedAmount).toBe(1200);
      expect(violation.autoGenerated).toBe(true);
      // Over the high-severity line: the cost is the only measure of damage an order carries.
      expect(violation.severity).toBe(Severity.HIGH);
    });

    it('charges a merchant with a one-off fee rather than an expense', async () => {
      const machine = await createMachine();
      const merchant = await createMerchant(representative.api, 'تاجر الصيانة');
      const order = await returnedOrder(machine.id);

      const closed = await closeOrder(order.id, {
        cost: 275,
        responsibleParty: ResponsibleParty.MERCHANT,
        responsibleMerchantId: merchant.id,
        paymentMethodId: undefined,
      });

      expect(closed.subscriptionId).not.toBeNull();
      expect(closed.financeTransactionId).toBeNull();

      const subscriptions = await ok<SubscriptionResponse[]>(
        director.get(`/merchants/${merchant.id}/subscriptions`),
      );
      const fee = subscriptions.find((row) => row.id === closed.subscriptionId)!;

      expect(fee.planType).toBe('ONE_TIME_FEE');
      expect(fee.amount).toBe(275);
      expect(fee.machineId).toBe(machine.id);
    });

    it('posts nothing when the factory bore the cost', async () => {
      const order = await returnedOrder((await createMachine()).id);

      const closed = await closeOrder(order.id, {
        cost: 900,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
      });

      expect(closed.financeTransactionId).toBeNull();
      expect(closed.violationId).toBeNull();
      expect(closed.subscriptionId).toBeNull();
      expect(await expensesFor(order.id)).toHaveLength(0);
    });

    it('demands a cost unless the repair was free', async () => {
      const order = await returnedOrder((await createMachine()).id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/close`, {
          result: MaintenanceResult.REPAIRED,
          isFreeUnderWarranty: false,
          responsibleParty: ResponsibleParty.COMPANY,
          paymentMethodId,
          returnedAt: RETURNED_AT,
        }),
        400,
        'COST_REQUIRED',
      );
    });

    it('demands a payment method when the company is paying', async () => {
      const order = await returnedOrder((await createMachine()).id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/close`, {
          result: MaintenanceResult.REPAIRED,
          isFreeUnderWarranty: false,
          cost: 120,
          responsibleParty: ResponsibleParty.COMPANY,
          returnedAt: RETURNED_AT,
        }),
        400,
        'VALIDATION_FAILED',
      );
    });

    it('carries the supplier and the invoice onto the expense', async () => {
      const supplier = await ok<{ id: string }>(
        director.post('/suppliers', { name: `ورشة ${uniqueCode('S')}`, phone: '01055500011' }),
        201,
      );

      const order = await returnedOrder((await createMachine()).id);
      const closed = await closeOrder(order.id, { cost: 640, supplierId: supplier.id });

      const posted = await expensesFor(order.id);
      expect(posted).toHaveLength(1);
      expect(posted[0].supplier?.id).toBe(supplier.id);
      expect(closed.financeTransactionId).toBe(posted[0].id);
    });

    it('refuses to correct the cost once an expense has been posted for it', async () => {
      const order = await returnedOrder((await createMachine()).id);
      await closeOrder(order.id, { cost: 300 });

      await fails(
        director.patch(`/maintenance-orders/${order.id}`, { cost: 250 }),
        422,
        'AUTO_TRANSACTION_IMMUTABLE',
      );
    });

    it('corrects the cost of a factory-borne close, and the machine total follows', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);

      await closeOrder(order.id, {
        cost: 500,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
      });
      expect((await readMachine(machine.id)).maintenance.totalRepairCost).toBe(500);

      const patched = await ok<MaintenanceOrderResponse>(
        director.patch(`/maintenance-orders/${order.id}`, { cost: 800 }),
      );

      expect(patched.cost).toBe(800);
      expect((await readMachine(machine.id)).maintenance.totalRepairCost).toBe(800);
    });
  });

  // ── the replacement chain ──────────────────────────────────────────────────

  describe('replacement', () => {
    it('rejects a REPLACED close with no replacement payload', async () => {
      const order = await returnedOrder((await createMachine()).id);

      await fails(
        director.post(`/maintenance-orders/${order.id}/close`, {
          result: MaintenanceResult.REPLACED,
          isFreeUnderWarranty: true,
          responsibleParty: ResponsibleParty.FACTORY,
          returnedAt: RETURNED_AT,
        }),
        400,
        'REPLACEMENT_PAYLOAD_REQUIRED',
      );

      expect((await readOrder(order.id)).status).toBe(MaintenanceStatus.RETURNED);
    });

    it('closes an order as a swap and hands over a new serial', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);
      const swap = factorySwap();

      const closed = await closeOrder(order.id, {
        result: MaintenanceResult.REPLACED,
        isFreeUnderWarranty: true,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
        replacement: swap,
      });

      expect(closed.replacementMachineId).not.toBeNull();

      const old = await readMachine(machine.id);
      expect(old.status).toBe(MachineStatus.REPLACED);
      expect(old.replacedByMachineId).toBe(closed.replacementMachineId);

      const replacement = await readMachine(closed.replacementMachineId!);
      expect(replacement.serial).toBe(swap.newSerial);
      expect(replacement.status).toBe(MachineStatus.IN_COMPANY_WAREHOUSE);
      expect(replacement.replacesMachineId).toBe(machine.id);
    });

    /** `12`, step 3: the same commercial asset, so its price and its age carry over. */
    it('gives the new unit the old one’s purchase price and purchase date', async () => {
      const machine = await createMachine({ purchasePrice: 3900 });
      const order = await returnedOrder(machine.id, factoryId);

      const closed = await closeOrder(order.id, {
        result: MaintenanceResult.REPLACED,
        isFreeUnderWarranty: true,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
        replacement: factorySwap(),
      });

      const replacement = await readMachine(closed.replacementMachineId!);
      expect(replacement.purchase.price).toBe(3900);
      expect(replacement.purchase.date).toBe('2025-02-10');
      expect(replacement.maintenance.repairCount).toBe(0);
      expect(replacement.maintenance.totalRepairCost).toBe(0);
    });

    it('swaps a machine that went to the factory and never came back as itself', async () => {
      const machine = await createMachine();
      const order = await openOrder(machine.id, factoryId);

      await ok<MaintenanceOrderResponse>(
        director.post(`/maintenance-orders/${order.id}/send`, {
          occurredAt: SENT_AT,
          signature: DRAWN,
        }),
      );

      const swapped = await ok<{
        oldMachineId: string;
        newMachineId: string;
        maintenanceOrderId: string | null;
      }>(director.post(`/machines/${machine.id}/replace`, factorySwap()), 201);

      expect(swapped.maintenanceOrderId).toBe(order.id);

      const concluded = await readOrder(order.id);
      expect(concluded.status).toBe(MaintenanceStatus.CLOSED);
      expect(concluded.result).toBe(MaintenanceResult.REPLACED);
      expect(concluded.responsibleParty).toBe(ResponsibleParty.FACTORY);
      expect(concluded.cost).toBe(0);

      expect((await readMachine(machine.id)).status).toBe(MachineStatus.REPLACED);
    });

    it('refuses to replace the same machine twice', async () => {
      const machine = await createMachine();
      await ok(director.post(`/machines/${machine.id}/replace`, factorySwap()), 201);

      await fails(
        director.post(`/machines/${machine.id}/replace`, factorySwap()),
        409,
        'MACHINE_ALREADY_REPLACED',
      );
    });

    it('refuses a replacement whose serial is already on the books', async () => {
      const taken = await createMachine();
      const machine = await createMachine();

      await fails(
        director.post(`/machines/${machine.id}/replace`, factorySwap({ newSerial: taken.serial })),
        409,
        'SERIAL_EXISTS',
      );
    });

    it('leaves the replaced machine read-only for transfers and for repairs', async () => {
      const machine = await createMachine();
      await ok(director.post(`/machines/${machine.id}/replace`, factorySwap()), 201);

      await fails(
        director.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.COMPANY_TO_BRANCH,
          toPartyId: supervisor.id,
          occurredAt: new Date().toISOString(),
          items: [{ machineId: machine.id, hasCharger: true, hasBox: true, condition: 'GOOD' }],
        }),
        422,
        'MACHINE_RETIRED',
      );

      await fails(
        director.post('/maintenance-orders', {
          machineId: machine.id,
          locationId: workshopId,
          reportedFault: 'عطل في ماكينة مستبدلة',
          sentAt: SENT_AT,
        }),
        409,
        'MACHINE_ALREADY_REPLACED',
      );
    });

    it('lists the swap from either side of it', async () => {
      const machine = await createMachine();
      const swapped = await ok<{ newMachineId: string }>(
        director.post(`/machines/${machine.id}/replace`, factorySwap()),
        201,
      );

      const fromOld = await okPage<ReplacementResponse>(
        director.get(`/replacements?machineId=${machine.id}`),
      );
      const fromNew = await okPage<ReplacementResponse>(
        director.get(`/replacements?machineId=${swapped.newMachineId}`),
      );

      expect(fromOld.items).toHaveLength(1);
      expect(fromNew.items).toHaveLength(1);
      expect(fromOld.items[0].id).toBe(fromNew.items[0].id);
      expect(fromOld.items[0].oldMachine.id).toBe(machine.id);
      expect(fromOld.items[0].newMachine.id).toBe(swapped.newMachineId);
    });
  });

  // ── the chain reads ────────────────────────────────────────────────────────

  describe('the replacement chain query', () => {
    let first: string;
    let second: string;
    let third: string;

    /**
     * A three-link chain with a repair on each of the first two links, built once: it is the
     * fixture every chain assertion below reads, and building it is eight requests.
     */
    beforeAll(async () => {
      const machine = await createMachine({ purchasePrice: 4200 });
      first = machine.id;

      const firstRepair = await returnedOrder(first);
      await closeOrder(firstRepair.id, { cost: 600 });

      const swapOne = await ok<{ newMachineId: string }>(
        director.post(`/machines/${first}/replace`, factorySwap()),
        201,
      );
      second = swapOne.newMachineId;

      const secondRepair = await returnedOrder(second);
      await closeOrder(secondRepair.id, { cost: 400 });

      const swapTwo = await ok<{ newMachineId: string }>(
        director.post(`/machines/${second}/replace`, factorySwap()),
        201,
      );
      third = swapTwo.newMachineId;
    });

    it('returns all three links from any of the three ids', async () => {
      for (const id of [first, second, third]) {
        const chain = await ok<ChainResponse>(director.get(`/machines/${id}/replacement-chain`));

        expect(chain.requestedMachineId).toBe(id);
        expect(chain.chainLength).toBe(3);
        expect(chain.chain.map((link) => link.id)).toEqual([first, second, third]);
        expect(chain.chain.map((link) => link.position)).toEqual([1, 2, 3]);
      }
    });

    it('marks only the live serial as current and closes the earlier windows', async () => {
      const chain = await ok<ChainResponse>(director.get(`/machines/${first}/replacement-chain`));

      expect(chain.chain.map((link) => link.isCurrent)).toEqual([false, false, true]);
      expect(chain.chain[0].activeTo).not.toBeNull();
      expect(chain.chain[2].activeTo).toBeNull();
      expect(chain.chain[0].replacedReason).toBe('لوحة رئيسية تالفة');
    });

    it('sums the repair costs across every link', async () => {
      const chain = await ok<ChainResponse>(director.get(`/machines/${third}/replacement-chain`));

      expect(chain.chainTotals.cumulativeRepairCost).toBe(1000);
      expect(chain.chainTotals.cumulativeRepairCount).toBe(2);
      expect(chain.chainTotals.purchasePrice).toBe(4200);
      expect(chain.chainTotals.costToValueRatio).toBe(0.24);
    });

    it('reads the cost summary through the chain, not off the current row', async () => {
      const summary = await ok<CostSummaryResponse>(
        director.get(`/machines/${third}/cost-summary`),
      );

      expect(summary.isInChain).toBe(true);
      expect(summary.chainLength).toBe(3);
      expect(summary.totalRepairCost).toBe(1000);
      expect(summary.chargedToCompany).toBe(1000);
      expect(summary.purchasePrice).toBe(4200);
      expect(summary.costToValueRatio).toBe(0.24);
    });

    it('gives a single machine a chain of one', async () => {
      const chain = await ok<ChainResponse>(
        director.get(`/machines/${(await createMachine()).id}/replacement-chain`),
      );

      expect(chain.chainLength).toBe(1);
      expect(chain.chain[0].isCurrent).toBe(true);
      expect(chain.chainTotals.cumulativeRepairCost).toBe(0);
    });
  });

  // ── the history reads ──────────────────────────────────────────────────────

  describe('history, totals and the timeline', () => {
    it('splits the repair bill by who paid it', async () => {
      const machine = await createMachine();
      const merchant = await createMerchant(representative.api, 'تاجر السجل');

      const paid = await returnedOrder(machine.id);
      await closeOrder(paid.id, { cost: 300 });

      const free = await returnedOrder(machine.id);
      await closeOrder(free.id, {
        isFreeUnderWarranty: true,
        cost: 700,
        responsibleParty: ResponsibleParty.FACTORY,
        paymentMethodId: undefined,
      });

      const charged = await returnedOrder(machine.id);
      await closeOrder(charged.id, {
        cost: 150,
        responsibleParty: ResponsibleParty.MERCHANT,
        responsibleMerchantId: merchant.id,
        paymentMethodId: undefined,
      });

      const history = await ok<MaintenanceHistoryResponse>(
        director.get(`/machines/${machine.id}/maintenance-history`),
      );

      expect(history.machineId).toBe(machine.id);
      expect(history.orders).toHaveLength(3);
      expect(history.totals).toMatchObject({
        orders: 3,
        totalCost: 450,
        freeUnderWarranty: 1,
        chargedToCompany: 300,
        chargedToMerchant: 150,
        chargedToRepresentative: 0,
      });
      expect(history.ordersMeta).toMatchObject({ total: 3, limit: 20 });

      const paged = await ok<MaintenanceHistoryResponse>(
        director.get(`/machines/${machine.id}/maintenance-history?limit=1`),
      );
      expect(paged.orders).toHaveLength(1);
      expect(paged.totals.orders).toBe(3);
      expect(paged.ordersMeta).toMatchObject({ total: 3, limit: 1, hasNext: true });
      await fails(
        director.get(`/machines/${machine.id}/maintenance-history?limit=1000`),
        400,
        'VALIDATION_FAILED',
      );

      const summary = await ok<CostSummaryResponse>(
        director.get(`/machines/${machine.id}/cost-summary`),
      );

      expect(summary.repairCount).toBe(3);
      expect(summary.chargedToCompany).toBe(300);
      expect(summary.chargedToMerchants).toBe(150);
      expect(summary.freeUnderWarranty).toBe(0);
    });

    it('withholds a ratio and a verdict from a machine with no purchase price', async () => {
      const machine = await createMachine({ purchasePrice: null });
      const order = await returnedOrder(machine.id);
      await closeOrder(order.id, { cost: 900 });

      const summary = await ok<CostSummaryResponse>(
        director.get(`/machines/${machine.id}/cost-summary`),
      );

      expect(summary.purchasePrice).toBeNull();
      expect(summary.costToValueRatio).toBeNull();
      expect(summary.totalRepairCost).toBe(900);
      expect(summary.recommendation).toBe('KEEP');
    });

    it('merges hand-offs, repairs and swaps into one stream, newest first', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);
      await closeOrder(order.id, { cost: 200 });

      const { items } = await okPage<TimelineEventResponse>(
        director.get(`/machines/${machine.id}/timeline?limit=50`),
      );

      const types = items.map((event) => event.type);
      expect(types).toContain('MAINTENANCE_OPENED');
      expect(types).toContain('MAINTENANCE_CLOSED');
      expect(types.filter((type) => type.startsWith('TRANSFER_'))).toHaveLength(2);

      const stamps = items.map((event) => Date.parse(event.at));
      expect(stamps).toEqual([...stamps].sort((a, b) => b - a));

      const closedEvent = items.find((event) => event.type === 'MAINTENANCE_CLOSED')!;
      expect(closedEvent.refNo).toBe(order.referenceNo);
      expect(closedEvent.details.result).toBe(MaintenanceResult.REPAIRED);
    });

    it('pages the timeline with a cursor', async () => {
      const machine = await createMachine();
      const order = await returnedOrder(machine.id);
      await closeOrder(order.id, { cost: 200 });

      const firstPage = await okPage<TimelineEventResponse>(
        director.get(`/machines/${machine.id}/timeline?limit=2`),
      );
      expect(firstPage.items).toHaveLength(2);

      const cursor = (firstPage.meta as unknown as { nextCursor: string | null }).nextCursor;
      expect(cursor).not.toBeNull();

      const secondPage = await okPage<TimelineEventResponse>(
        director.get(`/machines/${machine.id}/timeline?limit=2&cursor=${cursor}`),
      );

      const seen = new Set(firstPage.items.map((event) => `${event.type}:${event.refId}`));
      for (const event of secondPage.items) {
        expect(seen.has(`${event.type}:${event.refId}`)).toBe(false);
      }
    });

    it('filters the order list by machine, status and who paid', async () => {
      const machine = await createMachine();
      const closed = await returnedOrder(machine.id);
      await closeOrder(closed.id, { cost: 90 });

      const byMachine = await okPage<MaintenanceOrderResponse>(
        director.get(`/maintenance-orders?machineId=${machine.id}`),
      );
      expect(byMachine.items).toHaveLength(1);

      const byStatus = await okPage<MaintenanceOrderResponse>(
        director.get(
          `/maintenance-orders?machineId=${machine.id}&status=${MaintenanceStatus.OPEN}`,
        ),
      );
      expect(byStatus.items).toHaveLength(0);

      const byParty = await okPage<MaintenanceOrderResponse>(
        director.get(
          `/maintenance-orders?machineId=${machine.id}&responsibleParty=${ResponsibleParty.COMPANY}`,
        ),
      );
      expect(byParty.items.map((order) => order.id)).toEqual([closed.id]);
    });

    it('404s an unknown order rather than leaking that the id is well-formed', async () => {
      await fails(
        director.get(`/maintenance-orders/${randomUUID()}`),
        404,
        'MAINTENANCE_ORDER_NOT_FOUND',
      );
    });
  });

  // ── permissions ────────────────────────────────────────────────────────────

  describe('permissions', () => {
    it('refuses a representative the right to open an order', async () => {
      const machine = await createMachine();

      await fails(
        representative.api.post('/maintenance-orders', {
          machineId: machine.id,
          locationId: workshopId,
          reportedFault: 'عطل يبلغ عنه المندوب',
          sentAt: SENT_AT,
        }),
        403,
        'INSUFFICIENT_PERMISSIONS',
      );
    });

    it('refuses a representative the cost summary', async () => {
      const machine = await createMachine();

      await fails(
        representative.api.get(`/machines/${machine.id}/cost-summary`),
        403,
        'INSUFFICIENT_PERMISSIONS',
      );
    });

    /** A supervisor may report a fault: `maintenance.create` is on his role. */
    it('lets a supervisor open an order for a machine in his branch', async () => {
      const machine = await createMachine();

      const delivery = await ok<TransferResponse>(
        director.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.COMPANY_TO_BRANCH,
          toPartyId: supervisor.id,
          occurredAt: new Date().toISOString(),
          items: [{ machineId: machine.id, hasCharger: true, hasBox: true, condition: 'GOOD' }],
        }),
        201,
      );

      await ok(
        supervisor.api.post(`/transfers/${delivery.id}/confirm`, {
          signature: DRAWN,
          payloadHash: delivery.payloadHash,
        }),
      );

      // Back to the company warehouse, since that is where an order may be opened from.
      const home = await ok<TransferResponse>(
        supervisor.api.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.BRANCH_TO_COMPANY,
          toPartyId: companyWarehouseId,
          occurredAt: new Date().toISOString(),
          items: [{ machineId: machine.id, hasCharger: true, hasBox: true, condition: 'GOOD' }],
        }),
        201,
      );

      await ok(
        director.post(`/transfers/${home.id}/confirm`, {
          signature: DRAWN,
          payloadHash: home.payloadHash,
        }),
      );

      const opened = await ok<MaintenanceOrderResponse>(
        supervisor.api.post('/maintenance-orders', {
          machineId: machine.id,
          locationId: workshopId,
          reportedFault: 'عطل يبلغ عنه المشرف',
          sentAt: SENT_AT,
        }),
        201,
      );

      expect(opened.status).toBe(MaintenanceStatus.OPEN);
    });
  });
});
