import { randomUUID } from 'node:crypto';
import type { App } from 'supertest/types';
import { INestApplication } from '@nestjs/common';
import { MachineStatus } from 'src/common/enums/machine-status.enum';
import { Severity, ViolationStatus } from 'src/common/enums/operations.enum';
import { ItemCondition, SignatureMethod, TransferType } from 'src/common/enums/transfer.enum';
import { SystemRole } from 'src/modules/roles/entities/role.entity';
import { Api, fails, ok, okPage } from './utils/api-client';
import {
  createBranch,
  createMerchant,
  loginAsDirector,
  provisionUser,
  ProvisionedUser,
  roleIdByCode,
  uniqueCode,
} from './utils/fixtures';
import { createTestApp } from './utils/test-app';

interface MachineResponse {
  id: string;
  serial: string;
  status: MachineStatus;
  battery: { id: string; serial: string } | null;
}

interface MachineModelResponse {
  id: string;
  machineType: { id: string; requiresSim: boolean };
}

interface TransferResponse {
  id: string;
  status: string;
  payloadHash: string;
  items: { id: string; machine: { id: string } }[];
}

interface ViolationResponse {
  id: string;
  type: { id: string; code: string; name: string; defaultSeverity: Severity };
  user: { id: string; fullName: string };
  machine: { id: string; serial: string } | null;
  transferId: string | null;
  severity: Severity;
  status: ViolationStatus;
  description: string;
  chargedAmount: number | null;
  waiverReason: string | null;
  acknowledgedAt: string | null;
  autoGenerated: boolean;
  isEditable: boolean;
}

interface ViolationTypeResponse {
  id: string;
  code: string;
}

interface PaymentMethodResponse {
  id: string;
}

interface SummaryResponse {
  user: { id: string; fullName: string };
  branch: string | null;
  totals: { all: number; open: number; charged: number; waived: number };
  byType: { code: string; count: number; chargedAmount: number }[];
  bySeverity: Record<string, number>;
  totalCharged: number;
  last12Months: { month: string; count: number }[];
  trend: string;
}

const DRAWN = { method: SignatureMethod.DRAWN_SIGNATURE, deviceModel: 'e2e' };

describe('Violations (e2e)', () => {
  let app: INestApplication;
  let server: App;
  let director: Api;

  let branchId: string;
  let supervisor: ProvisionedUser;
  let representative: ProvisionedUser;

  let posModelId: string;
  let cashMethodId: string;
  let typesByCode: Map<string, string>;

  beforeAll(async () => {
    ({ app, server } = await createTestApp());
    director = await loginAsDirector(server);

    branchId = (await createBranch(director, 'فرع المخالفات')).id;

    supervisor = await provisionUser(server, director, {
      roleId: await roleIdByCode(director, SystemRole.BRANCH_SUPERVISOR),
      branchId,
      fullName: 'مشرف المخالفات',
    });

    representative = await provisionUser(server, director, {
      roleId: await roleIdByCode(director, SystemRole.REPRESENTATIVE),
      branchId,
      fullName: 'مندوب المخالفات',
    });

    const models = await ok<MachineModelResponse[]>(director.get('/machine-models'));
    posModelId = models.find((model) => model.machineType.requiresSim)!.id;

    const methods = await ok<PaymentMethodResponse[]>(director.get('/payment-methods'));
    cashMethodId = methods[0].id;

    const types = await ok<ViolationTypeResponse[]>(director.get('/violation-types'));
    typesByCode = new Map(types.map((type) => [type.code, type.id]));
  });

  afterAll(async () => {
    await app.close();
  });

  // ── fixtures ───────────────────────────────────────────────────────────────

  let serialCounter = 0;

  async function createMachine(): Promise<MachineResponse> {
    serialCounter += 1;
    const tag = `${uniqueCode('V')}_${serialCounter}`;

    return ok<MachineResponse>(
      director.post('/machines', {
        serial: `SN-${tag}`,
        machineModelId: posModelId,
        simSerial: `SIM-${tag}`,
        battery: { serial: `BT-${tag}` },
        hasBox: true,
      }),
      201,
    );
  }

  function item(
    machine: MachineResponse,
    overrides: Record<string, unknown> = {},
  ): Record<string, unknown> {
    return {
      machineId: machine.id,
      hasCharger: true,
      hasBox: true,
      condition: ItemCondition.GOOD,
      ...overrides,
    };
  }

  /** Company → branch → representative, so the return legs have something to act on. */
  async function issueToRepresentative(machine: MachineResponse): Promise<void> {
    const toBranch = await ok<TransferResponse>(
      director.post('/transfers', {
        clientUuid: randomUUID(),
        type: TransferType.COMPANY_TO_BRANCH,
        toPartyId: supervisor.id,
        occurredAt: new Date().toISOString(),
        items: [item(machine)],
      }),
      201,
    );

    await ok(
      supervisor.api.post(`/transfers/${toBranch.id}/confirm`, {
        signature: DRAWN,
        payloadHash: toBranch.payloadHash,
      }),
    );

    const toRep = await ok<TransferResponse>(
      supervisor.api.post('/transfers', {
        clientUuid: randomUUID(),
        type: TransferType.BRANCH_TO_REPRESENTATIVE,
        toPartyId: representative.id,
        occurredAt: new Date().toISOString(),
        items: [item(machine)],
      }),
      201,
    );

    await ok(
      representative.api.post(`/transfers/${toRep.id}/confirm`, {
        signature: DRAWN,
        payloadHash: toRep.payloadHash,
      }),
    );
  }

  /** The return leg the detector runs on. */
  async function returnToBranch(
    machine: MachineResponse,
    overrides: Record<string, unknown> = {},
  ): Promise<TransferResponse> {
    const created = await ok<TransferResponse>(
      representative.api.post('/transfers', {
        clientUuid: randomUUID(),
        type: TransferType.REPRESENTATIVE_TO_BRANCH,
        toPartyId: supervisor.id,
        occurredAt: new Date().toISOString(),
        items: [item(machine, overrides)],
      }),
      201,
    );

    return ok<TransferResponse>(
      supervisor.api.post(`/transfers/${created.id}/confirm`, {
        signature: DRAWN,
        payloadHash: created.payloadHash,
      }),
    );
  }

  function violationsFor(machineId: string): Promise<{ items: ViolationResponse[] }> {
    return okPage<ViolationResponse>(director.get(`/violations?machineId=${machineId}&limit=50`));
  }

  // ── auto-detection ─────────────────────────────────────────────────────────

  describe('auto-detection on a return leg', () => {
    /**
     * The acceptance criterion from `10`: returning a machine with a mismatched battery is
     * *accepted*, and a violation is filed against the man who returned it. Refusing the machine
     * would leave it in his car with no record, which is strictly worse.
     */
    it('accepts a mismatched battery and files exactly one violation', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);

      const confirmed = await returnToBranch(machine, {
        batterySerialScanned: 'BT-SOMETHING-ELSE',
      });

      expect(confirmed.status).toBe('CONFIRMED');
      expect((await ok<MachineResponse>(director.get(`/machines/${machine.id}`))).status).toBe(
        MachineStatus.IN_BRANCH_WAREHOUSE,
      );

      const { items } = await violationsFor(machine.id);
      const mismatch = items.filter((row) => row.type.code === 'BATTERY_MISMATCH');

      expect(mismatch).toHaveLength(1);
      expect(mismatch[0].severity).toBe(Severity.HIGH);
      expect(mismatch[0].autoGenerated).toBe(true);
      expect(mismatch[0].user.id).toBe(representative.id);
      expect(mismatch[0].status).toBe(ViolationStatus.OPEN);
      // The scanned serial goes in the description, so the supervisor sees what came back.
      expect(mismatch[0].description).toContain('BT-SOMETHING-ELSE');
    });

    it('files nothing when the machine comes back exactly as it went out', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, { batterySerialScanned: machine.battery!.serial });

      expect((await violationsFor(machine.id)).items).toHaveLength(0);
    });

    it('files a missing charger against the representative who lost it', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, { hasCharger: false });

      const { items } = await violationsFor(machine.id);
      const charger = items.filter((row) => row.type.code === 'MISSING_CHARGER');

      expect(charger).toHaveLength(1);
      expect(charger[0].severity).toBe(Severity.MEDIUM);
      expect(charger[0].user.id).toBe(representative.id);
    });

    it('files a missing box only for a unit that was issued boxed', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, { hasBox: false });

      const { items } = await violationsFor(machine.id);
      expect(items.map((row) => row.type.code)).toContain('MISSING_BOX');
    });

    it('files physical damage when a sound unit comes back broken', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, { condition: ItemCondition.NOT_WORKING });

      const { items } = await violationsFor(machine.id);
      const damage = items.filter((row) => row.type.code === 'PHYSICAL_DAMAGE');

      expect(damage).toHaveLength(1);
      expect(damage[0].severity).toBe(Severity.HIGH);
    });

    it('files every independent finding on one return', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, {
        batterySerialScanned: 'BT-WRONG',
        hasCharger: false,
        hasBox: false,
        condition: ItemCondition.DAMAGED,
      });

      const codes = (await violationsFor(machine.id)).items.map((row) => row.type.code).sort();

      expect(codes).toEqual(
        ['BATTERY_MISMATCH', 'MISSING_BOX', 'MISSING_CHARGER', 'PHYSICAL_DAMAGE'].sort(),
      );
    });

    /**
     * A device that loses the response retries the confirm. The partial unique index on
     * `(transfer_item_id, violation_type_id)` is what makes the replay a no-op rather than a
     * second entry on a man's file.
     */
    it('does not double-file when a confirm is replayed', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);

      const created = await ok<TransferResponse>(
        representative.api.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.REPRESENTATIVE_TO_BRANCH,
          toPartyId: supervisor.id,
          occurredAt: new Date().toISOString(),
          items: [item(machine, { hasCharger: false })],
        }),
        201,
      );

      await ok(
        supervisor.api.post(`/transfers/${created.id}/confirm`, {
          signature: DRAWN,
          payloadHash: created.payloadHash,
        }),
      );

      // The second confirm is refused as not-pending, and no second violation appears either way.
      await fails(
        supervisor.api.post(`/transfers/${created.id}/confirm`, {
          signature: DRAWN,
          payloadHash: created.payloadHash,
        }),
        422,
        'TRANSFER_NOT_PENDING',
      );

      const charger = (await violationsFor(machine.id)).items.filter(
        (row) => row.type.code === 'MISSING_CHARGER',
      );
      expect(charger).toHaveLength(1);
    });

    it('holds the representative responsible for what he gave a merchant', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);

      const merchantId = (await createMerchant(representative.api, 'تاجر المخالفات')).id;

      await ok(
        representative.api.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.REPRESENTATIVE_TO_MERCHANT,
          toPartyId: merchantId,
          occurredAt: new Date().toISOString(),
          items: [item(machine)],
          senderSignature: DRAWN,
        }),
        201,
      );

      await ok(
        representative.api.post('/transfers', {
          clientUuid: randomUUID(),
          type: TransferType.MERCHANT_TO_REPRESENTATIVE,
          toPartyId: representative.id,
          occurredAt: new Date().toISOString(),
          items: [item(machine, { hasCharger: false })],
          senderSignature: DRAWN,
        }),
        201,
      );

      const { items } = await violationsFor(machine.id);
      const charger = items.filter((row) => row.type.code === 'MISSING_CHARGER');

      expect(charger).toHaveLength(1);
      // The merchant has no account, so it lands on the man who placed the machine there.
      expect(charger[0].user.id).toBe(representative.id);
    });

    it('files nothing on an outbound leg', async () => {
      const machine = await createMachine();
      await issueToRepresentative(machine);

      expect((await violationsFor(machine.id)).items).toHaveLength(0);
    });
  });

  // ── the lifecycle ──────────────────────────────────────────────────────────

  describe('lifecycle', () => {
    async function anAutoViolation(): Promise<ViolationResponse> {
      const machine = await createMachine();
      await issueToRepresentative(machine);
      await returnToBranch(machine, { hasCharger: false });

      const { items } = await violationsFor(machine.id);
      return items.find((row) => row.type.code === 'MISSING_CHARGER')!;
    }

    it('lets the representative acknowledge his own violation', async () => {
      const violation = await anAutoViolation();

      const seen = await ok<ViolationResponse>(
        representative.api.post(`/violations/${violation.id}/acknowledge`),
      );

      expect(seen.status).toBe(ViolationStatus.ACKNOWLEDGED);
      expect(seen.acknowledgedAt).not.toBeNull();
    });

    /**
     * Rule 3 from `10`. A detected mismatch a supervisor can quietly rewrite is not evidence of
     * anything, and the argument it was meant to settle would be had again with the record itself
     * as the disputed exhibit.
     */
    it('refuses to edit an auto-generated violation', async () => {
      const violation = await anAutoViolation();

      expect(violation.isEditable).toBe(false);

      await fails(
        director.patch(`/violations/${violation.id}`, { severity: Severity.LOW }),
        422,
        'AUTO_VIOLATION_IMMUTABLE',
      );

      await fails(
        director.patch(`/violations/${violation.id}`, { description: 'شيء آخر تماماً' }),
        422,
        'AUTO_VIOLATION_IMMUTABLE',
      );
    });

    it('charges it once and refuses a second charge', async () => {
      const violation = await anAutoViolation();

      const charged = await ok<ViolationResponse>(
        director.post(`/violations/${violation.id}/charge`, {
          amount: 250,
          paymentMethodId: cashMethodId,
          chargedAt: new Date().toISOString(),
        }),
      );

      expect(charged.status).toBe(ViolationStatus.CHARGED);
      expect(charged.chargedAmount).toBe(250);

      await fails(
        director.post(`/violations/${violation.id}/charge`, {
          amount: 250,
          paymentMethodId: cashMethodId,
          chargedAt: new Date().toISOString(),
        }),
        409,
        'ALREADY_CHARGED',
      );
    });

    it('waives it with a reason and keeps the entry', async () => {
      const violation = await anAutoViolation();

      const waived = await ok<ViolationResponse>(
        director.post(`/violations/${violation.id}/waive`, {
          reason: 'الشاحن كان مفقوداً قبل التسليم',
        }),
      );

      expect(waived.status).toBe(ViolationStatus.WAIVED);
      expect(waived.waiverReason).toBe('الشاحن كان مفقوداً قبل التسليم');

      // Still there, still on his file.
      const reread = await ok<ViolationResponse>(director.get(`/violations/${violation.id}`));
      expect(reread.id).toBe(violation.id);
    });

    it('refuses a waiver with no reason', async () => {
      const violation = await anAutoViolation();

      await fails(
        director.post(`/violations/${violation.id}/waive`, { reason: 'لا' }),
        400,
        'VALIDATION_FAILED',
      );
    });

    it('will not waive something already charged', async () => {
      const violation = await anAutoViolation();

      await ok(
        director.post(`/violations/${violation.id}/charge`, {
          amount: 100,
          paymentMethodId: cashMethodId,
          chargedAt: new Date().toISOString(),
        }),
      );

      await fails(
        director.post(`/violations/${violation.id}/waive`, { reason: 'تراجعنا عن التحصيل' }),
        409,
        'ALREADY_CHARGED',
      );
    });
  });

  // ── filing by hand ─────────────────────────────────────────────────────────

  describe('manual entry', () => {
    it('files one and allows it to be revised', async () => {
      const created = await ok<ViolationResponse>(
        supervisor.api.post('/violations', {
          violationTypeId: typesByCode.get('OTHER')!,
          userId: representative.id,
          severity: Severity.LOW,
          description: 'تأخر في تسليم كشف الحساب',
        }),
        201,
      );

      expect(created.autoGenerated).toBe(false);
      expect(created.isEditable).toBe(true);

      const revised = await ok<ViolationResponse>(
        director.patch(`/violations/${created.id}`, { severity: Severity.MEDIUM }),
      );

      expect(revised.severity).toBe(Severity.MEDIUM);
    });

    it('rejects an unknown violation type', async () => {
      await fails(
        supervisor.api.post('/violations', {
          violationTypeId: randomUUID(),
          userId: representative.id,
          severity: Severity.LOW,
          description: 'نوع غير معروف',
        }),
        400,
        'VALIDATION_FAILED',
      );
    });

    it('refuses a representative the right to file against anyone', async () => {
      await fails(
        representative.api.post('/violations', {
          violationTypeId: typesByCode.get('OTHER')!,
          userId: supervisor.id,
          severity: Severity.HIGH,
          description: 'محاولة',
        }),
        403,
        'INSUFFICIENT_PERMISSIONS',
      );
    });
  });

  // ── who sees what ──────────────────────────────────────────────────────────

  it('lets a representative read his own file even scoped to one branch', async () => {
    const machine = await createMachine();
    await issueToRepresentative(machine);
    await returnToBranch(machine, { hasCharger: false });

    const { items } = await okPage<ViolationResponse>(
      representative.api.get('/violations?limit=100'),
    );

    expect(items.every((row) => row.user.id === representative.id)).toBe(true);
    expect(items.length).toBeGreaterThan(0);
  });

  // ── the summary ────────────────────────────────────────────────────────────

  describe('the summary a director opens', () => {
    it('totals the file by status, type and severity', async () => {
      const subject = await provisionUser(server, director, {
        roleId: await roleIdByCode(director, SystemRole.REPRESENTATIVE),
        branchId,
        fullName: 'مندوب للملخص',
      });

      const typeId = typesByCode.get('OTHER')!;

      const open = await ok<ViolationResponse>(
        supervisor.api.post('/violations', {
          violationTypeId: typeId,
          userId: subject.id,
          severity: Severity.HIGH,
          description: 'مخالفة مفتوحة',
        }),
        201,
      );

      const toCharge = await ok<ViolationResponse>(
        supervisor.api.post('/violations', {
          violationTypeId: typeId,
          userId: subject.id,
          severity: Severity.MEDIUM,
          description: 'مخالفة للتحصيل',
        }),
        201,
      );

      const toWaive = await ok<ViolationResponse>(
        supervisor.api.post('/violations', {
          violationTypeId: typeId,
          userId: subject.id,
          severity: Severity.LOW,
          description: 'مخالفة للإعفاء',
        }),
        201,
      );

      await ok(
        director.post(`/violations/${toCharge.id}/charge`, {
          amount: 400,
          paymentMethodId: cashMethodId,
          chargedAt: new Date().toISOString(),
        }),
      );

      await ok(director.post(`/violations/${toWaive.id}/waive`, { reason: 'ظرف قهري موثق' }));

      const summary = await ok<SummaryResponse>(
        director.get(`/users/${subject.id}/violations/summary`),
      );

      expect(summary.user.id).toBe(subject.id);
      expect(summary.branch).toBe('فرع المخالفات');
      expect(summary.totals).toEqual({ all: 3, open: 1, charged: 1, waived: 1 });
      expect(summary.bySeverity).toEqual({ HIGH: 1, MEDIUM: 1, LOW: 1 });
      expect(summary.totalCharged).toBe(400);

      const other = summary.byType.find((row) => row.code === 'OTHER')!;
      expect(other.count).toBe(3);
      expect(other.chargedAmount).toBe(400);

      // Twelve buckets including the empty ones — a gap in a chart is information.
      expect(summary.last12Months).toHaveLength(12);
      expect(summary.last12Months.at(-1)!.count).toBe(3);

      expect(['IMPROVING', 'STEADY', 'WORSENING']).toContain(summary.trend);

      void open;
    });

    it('lets a representative pull his own summary', async () => {
      const summary = await ok<SummaryResponse>(
        representative.api.get(`/users/${representative.id}/violations/summary`),
      );

      expect(summary.user.id).toBe(representative.id);
    });
  });
});
