import { ApiProperty } from '@nestjs/swagger';
import {
  SEVERITIES,
  Severity,
  VIOLATION_STATUSES,
  ViolationStatus,
} from 'src/common/enums/operations.enum';

export class ViolationTypeRefResponse {
  @ApiProperty({ format: 'uuid' }) id: string;
  @ApiProperty({ example: 'BATTERY_MISMATCH' }) code: string;
  @ApiProperty({ example: 'بطارية غير مطابقة' }) name: string;
  @ApiProperty({ enum: SEVERITIES }) defaultSeverity: Severity;
}

export class ViolationUserRefResponse {
  @ApiProperty({ format: 'uuid' }) id: string;
  @ApiProperty({ example: 'أحمد سالم' }) fullName: string;
}

export class ViolationMachineRefResponse {
  @ApiProperty({ format: 'uuid' }) id: string;
  @ApiProperty({ example: 'SN-00341' }) serial: string;
}

export class ViolationResponse {
  @ApiProperty({ format: 'uuid' }) id: string;
  @ApiProperty({ type: ViolationTypeRefResponse }) type: ViolationTypeRefResponse;
  @ApiProperty({ type: ViolationUserRefResponse }) user: ViolationUserRefResponse;

  @ApiProperty({ type: ViolationMachineRefResponse, nullable: true })
  machine: ViolationMachineRefResponse | null;

  @ApiProperty({ format: 'uuid', nullable: true }) transferId: string | null;
  @ApiProperty({ enum: SEVERITIES }) severity: Severity;
  @ApiProperty({ enum: VIOLATION_STATUSES }) status: ViolationStatus;
  @ApiProperty() description: string;

  @ApiProperty({ nullable: true, description: 'Null until charged.' })
  chargedAmount: number | null;

  @ApiProperty({ nullable: true }) chargedAt: string | null;
  @ApiProperty({ nullable: true }) waiverReason: string | null;
  @ApiProperty({ nullable: true }) acknowledgedAt: string | null;
  @ApiProperty({ nullable: true }) resolvedAt: string | null;

  @ApiProperty({ description: 'Raised by the return-leg detector rather than typed by a person.' })
  autoGenerated: boolean;

  @ApiProperty({
    description: 'False for auto-generated rows — they may only be waived or charged.',
  })
  isEditable: boolean;

  @ApiProperty() createdAt: string;
}

export class ViolationTotalsResponse {
  @ApiProperty() all: number;
  @ApiProperty() open: number;
  @ApiProperty() charged: number;
  @ApiProperty() waived: number;
}

export class ViolationByTypeResponse {
  @ApiProperty({ example: 'BATTERY_MISMATCH' }) code: string;
  @ApiProperty({ example: 'بطارية غير مطابقة' }) name: string;
  @ApiProperty() count: number;
  @ApiProperty() chargedAmount: number;
}

export class ViolationMonthResponse {
  @ApiProperty({ example: '2026-04' }) month: string;
  @ApiProperty() count: number;
}

/** The screen a Director opens before deciding anything about a representative (`10`). */
export class ViolationSummaryResponse {
  @ApiProperty({ type: ViolationUserRefResponse }) user: ViolationUserRefResponse;
  @ApiProperty({ nullable: true }) branch: string | null;
  @ApiProperty({ type: ViolationTotalsResponse }) totals: ViolationTotalsResponse;
  @ApiProperty({ type: [ViolationByTypeResponse] }) byType: ViolationByTypeResponse[];

  @ApiProperty({ description: 'Counts keyed by LOW / MEDIUM / HIGH.' })
  bySeverity: Record<Severity, number>;

  @ApiProperty() totalCharged: number;
  @ApiProperty({ type: [ViolationMonthResponse] }) last12Months: ViolationMonthResponse[];

  @ApiProperty({
    enum: ['IMPROVING', 'STEADY', 'WORSENING'],
    description: 'The last six months against the six before them.',
  })
  trend: string;
}
