import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:machinery/core/constants/locale_keys.dart';
import 'package:machinery/core/lookups/lookup_entity.dart';
import 'package:machinery/core/shared_widgets/custom_button.dart';
import 'package:machinery/core/shared_widgets/filter_choice_row.dart';
import 'package:machinery/core/shared_widgets/filter_section.dart';
import 'package:machinery/core/theme/styles/app_colors.dart';
import 'package:machinery/core/theme/styles/app_spacing.dart';
import 'package:machinery/core/theme/styles/app_text_styles.dart';
import 'package:machinery/core/utils/enums.dart';
import 'package:machinery/feature/violations/domain/params/violations_query_params.dart';
import 'package:machinery/feature/violations/presentation/helpers/violation_labels.dart';

/// The violations filter sheet.
///
/// Status and severity are both multi-select: "everything still open" and
/// "everything serious" are the two questions this register gets asked, and
/// neither is a single value.
class ViolationsFilterSheet extends StatefulWidget {
  const ViolationsFilterSheet({
    required this.types,
    required this.current,
    super.key,
  });

  final List<LookupEntity> types;
  final ViolationsQueryParams current;

  static Future<ViolationsQueryParams?> show({
    required BuildContext context,
    required List<LookupEntity> types,
    required ViolationsQueryParams current,
  }) {
    return showModalBottomSheet<ViolationsQueryParams>(
      context: context,
      isScrollControlled: true,
      backgroundColor: AppColors.surfaceColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(AppRadius.lg)),
      ),
      builder: (_) => ViolationsFilterSheet(types: types, current: current),
    );
  }

  @override
  State<ViolationsFilterSheet> createState() => _ViolationsFilterSheetState();
}

class _ViolationsFilterSheetState extends State<ViolationsFilterSheet> {
  late Set<ViolationStatus> _statuses;
  late Set<ViolationSeverity> _severities;
  String? _typeId;
  bool _autoOnly = false;

  @override
  void initState() {
    super.initState();
    _statuses = widget.current.statuses.toSet();
    _severities = widget.current.severities.toSet();
    _typeId = widget.current.typeId;
    _autoOnly = widget.current.autoGeneratedOnly;
  }

  ViolationsQueryParams get _result {
    return widget.current.copyWith(
      page: 1,
      statuses: _statuses.toList(growable: false),
      severities: _severities.toList(growable: false),
      typeId: _typeId,
      autoGeneratedOnly: _autoOnly,
      resetType: _typeId == null,
    );
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: ConstrainedBox(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.sizeOf(context).height * 0.85,
        ),
        child: SingleChildScrollView(
          padding: const EdgeInsetsDirectional.all(AppSpacing.lg),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                LocaleKeys.violationsFilterTitle.tr(),
                style: Styles.s17(context),
              ),
              const SizedBox(height: AppSpacing.lg),

              FilterSection(
                title: LocaleKeys.violationsFilterStatus.tr(),
                child: _ToggleChips<ViolationStatus>(
                  options: ViolationLabels.filterableStatuses,
                  selected: _statuses,
                  labelOf: ViolationLabels.status,
                  onToggle: (ViolationStatus status) => setState(() {
                    if (!_statuses.remove(status)) {
                      _statuses.add(status);
                    }
                  }),
                ),
              ),

              FilterSection(
                title: LocaleKeys.violationsFilterSeverity.tr(),
                child: _ToggleChips<ViolationSeverity>(
                  options: ViolationLabels.filterableSeverities,
                  selected: _severities,
                  labelOf: ViolationLabels.severity,
                  onToggle: (ViolationSeverity severity) => setState(() {
                    if (!_severities.remove(severity)) {
                      _severities.add(severity);
                    }
                  }),
                ),
              ),

              if (widget.types.isNotEmpty)
                FilterSection(
                  title: LocaleKeys.violationType.tr(),
                  child: FilterChoiceRow(
                    labels: <String>[
                      LocaleKeys.userFilterAll.tr(),
                      ...widget.types.map((LookupEntity t) => t.name),
                    ],
                    values: <String?>[
                      null,
                      ...widget.types.map((LookupEntity t) => t.id),
                    ],
                    selected: _typeId,
                    onSelected: (String? value) =>
                        setState(() => _typeId = value),
                  ),
                ),

              SwitchListTile.adaptive(
                contentPadding: EdgeInsets.zero,
                value: _autoOnly,
                onChanged: (bool value) => setState(() => _autoOnly = value),
                title: Text(
                  LocaleKeys.violationsFilterAutoOnly.tr(),
                  style: Styles.s14(context),
                ),
              ),

              const SizedBox(height: AppSpacing.lg),
              CustomButton(
                title: LocaleKeys.confirm.tr(),
                isLoading: false,
                height: 48,
                identifier: 'violations_filter_apply',
                onPressed: () => Navigator.of(context).pop(_result),
              ),
              const SizedBox(height: AppSpacing.sm),
              CustomButton(
                title: LocaleKeys.userClearFilters.tr(),
                isLoading: false,
                isStroked: true,
                height: 48,
                onPressed: () =>
                    Navigator.of(context).pop(widget.current.cleared()),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Multi-select chips. Unlike [FilterChoiceRow] these toggle independently, so
/// there is no "all" chip — no selection already means all.
class _ToggleChips<T> extends StatelessWidget {
  const _ToggleChips({
    required this.options,
    required this.selected,
    required this.labelOf,
    required this.onToggle,
  });

  final List<T> options;
  final Set<T> selected;
  final String Function(T) labelOf;
  final ValueChanged<T> onToggle;

  @override
  Widget build(BuildContext context) {
    return Wrap(
      spacing: AppSpacing.sm,
      runSpacing: AppSpacing.sm,
      children: options
          .map((T option) {
            final bool isSelected = selected.contains(option);

            return FilterChip(
              label: Text(labelOf(option), style: Styles.s13(context)),
              selected: isSelected,
              onSelected: (_) => onToggle(option),
              showCheckmark: false,
              backgroundColor: AppColors.surfaceAltColor,
              selectedColor: AppColors.primaryLightColor,
              side: BorderSide(
                color: isSelected
                    ? AppColors.primaryColor
                    : AppColors.borderColor,
              ),
            );
          })
          .toList(growable: false),
    );
  }
}
