/**
 * Stable, machine-readable error codes. The Flutter client switches on these strings.
 * Never change the meaning of an existing code — add a new one instead.
 */
export const ErrorCode = {
  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  CLIENT_UPGRADE_REQUIRED: 'CLIENT_UPGRADE_REQUIRED',

  // auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  BRANCH_SCOPE_VIOLATION: 'BRANCH_SCOPE_VIOLATION',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  DEVICE_NOT_ENROLLED: 'DEVICE_NOT_ENROLLED',

  // machines
  SERIAL_EXISTS: 'SERIAL_EXISTS',
  BATTERY_SERIAL_EXISTS: 'BATTERY_SERIAL_EXISTS',
  SIM_SERIAL_EXISTS: 'SIM_SERIAL_EXISTS',
  BOX_SERIAL_EXISTS: 'BOX_SERIAL_EXISTS',
  SERIAL_IMMUTABLE: 'SERIAL_IMMUTABLE',
  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  MACHINE_RETIRED: 'MACHINE_RETIRED',
  MACHINE_ALREADY_REPLACED: 'MACHINE_ALREADY_REPLACED',

  // transfers
  INVALID_MACHINE_STATUS: 'INVALID_MACHINE_STATUS',
  NOT_IN_YOUR_CUSTODY: 'NOT_IN_YOUR_CUSTODY',
  MACHINE_ALREADY_IN_TRANSIT: 'MACHINE_ALREADY_IN_TRANSIT',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_NOT_PENDING: 'TRANSFER_NOT_PENDING',
  PAYLOAD_CHANGED: 'PAYLOAD_CHANGED',
  INVALID_TRANSFER_TYPE: 'INVALID_TRANSFER_TYPE',
  INTER_BRANCH_DIRECT_TRANSFER_NOT_ALLOWED: 'INTER_BRANCH_DIRECT_TRANSFER_NOT_ALLOWED',
  SIGNATURE_REQUIRED: 'SIGNATURE_REQUIRED',
  CANCEL_WINDOW_EXPIRED: 'CANCEL_WINDOW_EXPIRED',
  NOT_THE_RECEIVER: 'NOT_THE_RECEIVER',
  NOT_THE_SENDER: 'NOT_THE_SENDER',

  // maintenance
  MACHINE_ALREADY_IN_MAINTENANCE: 'MACHINE_ALREADY_IN_MAINTENANCE',
  ORDER_ALREADY_CLOSED: 'ORDER_ALREADY_CLOSED',
  COST_REQUIRED: 'COST_REQUIRED',
  REPLACEMENT_PAYLOAD_REQUIRED: 'REPLACEMENT_PAYLOAD_REQUIRED',
  MAINTENANCE_ORDER_NOT_FOUND: 'MAINTENANCE_ORDER_NOT_FOUND',
  INVALID_MAINTENANCE_STATUS: 'INVALID_MAINTENANCE_STATUS',

  // decommission
  MACHINE_NOT_IN_WAREHOUSE: 'MACHINE_NOT_IN_WAREHOUSE',
  OPEN_MAINTENANCE_ORDER: 'OPEN_MAINTENANCE_ORDER',
  ALREADY_DECOMMISSIONED: 'ALREADY_DECOMMISSIONED',
  DECOMMISSION_NOT_FOUND: 'DECOMMISSION_NOT_FOUND',

  // settings
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',

  // merchants
  MERCHANT_HAS_MACHINES: 'MERCHANT_HAS_MACHINES',
  DUPLICATE_NATIONAL_ID: 'DUPLICATE_NATIONAL_ID',

  // finance
  CATEGORY_KIND_MISMATCH: 'CATEGORY_KIND_MISMATCH',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_TRANSACTIONS: 'CATEGORY_HAS_TRANSACTIONS',
  CIRCULAR_CATEGORY_REFERENCE: 'CIRCULAR_CATEGORY_REFERENCE',
  SYSTEM_CATEGORY_PROTECTED: 'SYSTEM_CATEGORY_PROTECTED',
  FUTURE_DATE_NOT_ALLOWED: 'FUTURE_DATE_NOT_ALLOWED',
  BACKDATE_LIMIT_EXCEEDED: 'BACKDATE_LIMIT_EXCEEDED',
  AUTO_TRANSACTION_IMMUTABLE: 'AUTO_TRANSACTION_IMMUTABLE',
  TRANSACTION_ALREADY_VOIDED: 'TRANSACTION_ALREADY_VOIDED',
  OVERLAPPING_BUDGET: 'OVERLAPPING_BUDGET',
  BUDGET_ON_INCOME_CATEGORY: 'BUDGET_ON_INCOME_CATEGORY',
  EDIT_WINDOW_EXPIRED: 'EDIT_WINDOW_EXPIRED',

  // reports
  EXPORT_FORMAT_UNAVAILABLE: 'EXPORT_FORMAT_UNAVAILABLE',

  // violations
  ALREADY_CHARGED: 'ALREADY_CHARGED',
  AUTO_VIOLATION_IMMUTABLE: 'AUTO_VIOLATION_IMMUTABLE',

  // users
  USER_HAS_CUSTODY: 'USER_HAS_CUSTODY',
  LAST_DIRECTOR: 'LAST_DIRECTOR',
  CANNOT_EDIT_OWN_PERMISSIONS: 'CANNOT_EDIT_OWN_PERMISSIONS',
  SYSTEM_ROLE_PROTECTED: 'SYSTEM_ROLE_PROTECTED',
  PHONE_EXISTS: 'PHONE_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  BRANCH_REQUIRED_FOR_ROLE: 'BRANCH_REQUIRED_FOR_ROLE',

  // branches
  BRANCH_HAS_MACHINES: 'BRANCH_HAS_MACHINES',
  BRANCH_HAS_ACTIVE_STAFF: 'BRANCH_HAS_ACTIVE_STAFF',
  BRANCH_CODE_EXISTS: 'BRANCH_CODE_EXISTS',
  WAREHOUSE_TYPE_CONFLICT: 'WAREHOUSE_TYPE_CONFLICT',

  // lookups / localization
  CODE_EXISTS: 'CODE_EXISTS',
  DEFAULT_LOCALE_REQUIRED: 'DEFAULT_LOCALE_REQUIRED',
  LOOKUP_IN_USE: 'LOOKUP_IN_USE',

  // sync / media
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENT_REQUEST_IN_PROGRESS: 'IDEMPOTENT_REQUEST_IN_PROGRESS',
  INVALID_OCCURRED_AT: 'INVALID_OCCURRED_AT',
  SCHEMA_VERSION_MISMATCH: 'SCHEMA_VERSION_MISMATCH',
  TOO_MANY_PHOTOS: 'TOO_MANY_PHOTOS',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_NOT_CONFIRMED: 'MEDIA_NOT_CONFIRMED',
  MEDIA_ALREADY_USED: 'MEDIA_ALREADY_USED',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
