import 'package:equatable/equatable.dart';
import 'package:machinery/core/utils/enums.dart';

/// Something that went wrong on a return, charged to whoever was holding the
/// machine.
///
/// Most of these are raised by the server itself when a return leg is signed
/// for — a battery that came back with a different serial, a charger that did
/// not come back at all. Those cannot be edited afterwards: the record is what
/// the two signatures agreed on, and rewriting it would make the signature
/// meaningless. They can only be charged or waived.
class ViolationEntity extends Equatable {
  const ViolationEntity({
    required this.id,
    required this.type,
    required this.user,
    required this.severity,
    required this.status,
    required this.description,
    required this.autoGenerated,
    required this.isEditable,
    this.machine,
    this.transferId,
    this.chargedAmount,
    this.chargedAt,
    this.waiverReason,
    this.acknowledgedAt,
    this.resolvedAt,
    this.createdAt,
  });

  final String id;
  final ViolationTypeRef type;

  /// Who is answerable. On a merchant return that is the representative, not
  /// the merchant — the merchant never signed for anything.
  final ViolationUserRef user;

  final ViolationMachineRef? machine;
  final String? transferId;
  final ViolationSeverity severity;
  final ViolationStatus status;
  final String description;

  final double? chargedAmount;
  final DateTime? chargedAt;
  final String? waiverReason;
  final DateTime? acknowledgedAt;
  final DateTime? resolvedAt;
  final DateTime? createdAt;

  /// Raised by the return-leg detector rather than typed by a person.
  final bool autoGenerated;

  /// False for auto-generated rows, which the server refuses to patch.
  final bool isEditable;

  /// Charged and waived are both endings. Nothing further can be done to a
  /// violation in either state, so the action row disappears.
  bool get isSettled =>
      status == ViolationStatus.charged ||
      status == ViolationStatus.waived ||
      status == ViolationStatus.closed;

  /// Acknowledging is a one-time step, only from open, and only by the person
  /// the violation is against.
  ///
  /// The subject check is not a nicety: acknowledgement is that man saying he
  /// has seen it, so a colleague cannot make the statement for him and the
  /// server refuses it with a 403. Showing the button to a supervisor reading
  /// one of his representatives' records would offer an action that can only
  /// fail.
  bool canAcknowledgeBy(String? currentUserId) =>
      status == ViolationStatus.open &&
      currentUserId != null &&
      currentUserId == user.id;

  @override
  List<Object?> get props => <Object?>[
    id,
    type,
    user,
    machine,
    transferId,
    severity,
    status,
    description,
    chargedAmount,
    chargedAt,
    waiverReason,
    acknowledgedAt,
    resolvedAt,
    autoGenerated,
    isEditable,
  ];
}

class ViolationTypeRef extends Equatable {
  const ViolationTypeRef({
    required this.id,
    required this.code,
    required this.name,
    required this.defaultSeverity,
  });

  final String id;
  final String code;
  final String name;
  final ViolationSeverity defaultSeverity;

  @override
  List<Object?> get props => <Object?>[id, code, name, defaultSeverity];
}

class ViolationUserRef extends Equatable {
  const ViolationUserRef({required this.id, required this.fullName});

  final String id;
  final String fullName;

  @override
  List<Object?> get props => <Object?>[id, fullName];
}

class ViolationMachineRef extends Equatable {
  const ViolationMachineRef({required this.id, required this.serial});

  final String id;
  final String serial;

  @override
  List<Object?> get props => <Object?>[id, serial];
}

/// The screen a Director opens before deciding anything about a representative:
/// how many, of what kind, how much it has cost, and whether it is getting
/// better or worse.
class ViolationSummary extends Equatable {
  const ViolationSummary({
    required this.user,
    required this.totals,
    required this.trend,
    this.branch,
    this.byType = const <ViolationTypeCount>[],
    this.bySeverity = const <ViolationSeverity, int>{},
    this.totalCharged = 0,
    this.last12Months = const <ViolationMonthCount>[],
  });

  final ViolationUserRef user;
  final String? branch;
  final ViolationTotals totals;
  final List<ViolationTypeCount> byType;
  final Map<ViolationSeverity, int> bySeverity;
  final double totalCharged;
  final List<ViolationMonthCount> last12Months;

  /// The last six months against the six before them, judged server-side.
  final ViolationTrend trend;

  @override
  List<Object?> get props => <Object?>[
    user,
    branch,
    totals,
    byType,
    bySeverity,
    totalCharged,
    last12Months,
    trend,
  ];
}

class ViolationTotals extends Equatable {
  const ViolationTotals({
    this.all = 0,
    this.open = 0,
    this.charged = 0,
    this.waived = 0,
  });

  final int all;
  final int open;
  final int charged;
  final int waived;

  @override
  List<Object?> get props => <Object?>[all, open, charged, waived];
}

class ViolationTypeCount extends Equatable {
  const ViolationTypeCount({
    required this.code,
    required this.name,
    required this.count,
    this.chargedAmount = 0,
  });

  final String code;
  final String name;
  final int count;
  final double chargedAmount;

  @override
  List<Object?> get props => <Object?>[code, name, count, chargedAmount];
}

class ViolationMonthCount extends Equatable {
  const ViolationMonthCount({required this.month, required this.count});

  /// `yyyy-MM`, which is what the chart's axis is labelled from.
  final String month;

  final int count;

  @override
  List<Object?> get props => <Object?>[month, count];
}
