import 'package:equatable/equatable.dart';
import 'package:machinery/core/constants/api_keys.dart';
import 'package:machinery/core/utils/enums.dart';

/// The filter set behind `GET /violations`. Held as one object so the list cubit
/// carries the current filters across a refresh.
class ViolationsQueryParams extends Equatable {
  const ViolationsQueryParams({
    this.page = 1,
    this.limit = 20,
    this.userId,
    this.machineId,
    this.typeId,
    this.branchId,
    this.statuses = const <ViolationStatus>[],
    this.severities = const <ViolationSeverity>[],
    this.dateFrom,
    this.dateTo,
    this.autoGeneratedOnly = false,
  });

  final int page;
  final int limit;

  /// Whose record this is. A representative reading his own passes his own id
  /// rather than a separate "mine" endpoint.
  final String? userId;

  final String? machineId;
  final String? typeId;
  final String? branchId;
  final List<ViolationStatus> statuses;
  final List<ViolationSeverity> severities;
  final String? dateFrom;
  final String? dateTo;

  /// Splits what the return-leg detector raised from what a supervisor typed.
  final bool autoGeneratedOnly;

  bool get hasFilters =>
      userId != null ||
      machineId != null ||
      typeId != null ||
      branchId != null ||
      statuses.isNotEmpty ||
      severities.isNotEmpty ||
      dateFrom != null ||
      dateTo != null ||
      autoGeneratedOnly;

  int get activeFilterCount => <bool>[
    userId != null,
    machineId != null,
    typeId != null,
    branchId != null,
    statuses.isNotEmpty,
    severities.isNotEmpty,
    dateFrom != null || dateTo != null,
    autoGeneratedOnly,
  ].where((bool active) => active).length;

  ViolationsQueryParams copyWith({
    int? page,
    int? limit,
    String? userId,
    String? machineId,
    String? typeId,
    String? branchId,
    List<ViolationStatus>? statuses,
    List<ViolationSeverity>? severities,
    String? dateFrom,
    String? dateTo,
    bool? autoGeneratedOnly,
    bool resetUser = false,
    bool resetMachine = false,
    bool resetType = false,
    bool resetBranch = false,
    bool resetDates = false,
  }) {
    return ViolationsQueryParams(
      page: page ?? this.page,
      limit: limit ?? this.limit,
      userId: resetUser ? null : (userId ?? this.userId),
      machineId: resetMachine ? null : (machineId ?? this.machineId),
      typeId: resetType ? null : (typeId ?? this.typeId),
      branchId: resetBranch ? null : (branchId ?? this.branchId),
      statuses: statuses ?? this.statuses,
      severities: severities ?? this.severities,
      dateFrom: resetDates ? null : (dateFrom ?? this.dateFrom),
      dateTo: resetDates ? null : (dateTo ?? this.dateTo),
      autoGeneratedOnly: autoGeneratedOnly ?? this.autoGeneratedOnly,
    );
  }

  /// Keeps whatever scoped this list — a machine's violations stay that
  /// machine's after "clear all".
  ViolationsQueryParams cleared() => ViolationsQueryParams(
    page: 1,
    limit: limit,
    userId: userId,
    machineId: machineId,
  );

  Map<String, dynamic> toQuery() {
    return <String, dynamic>{
      ApiKeys.page: page,
      ApiKeys.limit: limit,
      if (userId != null) ApiKeys.userId: userId,
      if (machineId != null) ApiKeys.machineId: machineId,
      if (typeId != null) ApiKeys.typeId: typeId,
      if (branchId != null) ApiKeys.branchId: branchId,
      if (statuses.isNotEmpty)
        ApiKeys.status: statuses
            .map((ViolationStatus status) => status.value)
            .toList(growable: false),
      if (severities.isNotEmpty)
        ApiKeys.severity: severities
            .map((ViolationSeverity severity) => severity.value)
            .toList(growable: false),
      if (dateFrom != null) ApiKeys.dateFrom: dateFrom,
      if (dateTo != null) ApiKeys.dateTo: dateTo,
      if (autoGeneratedOnly) ApiKeys.autoGenerated: true,
    };
  }

  @override
  List<Object?> get props => <Object?>[
    page,
    limit,
    userId,
    machineId,
    typeId,
    branchId,
    statuses,
    severities,
    dateFrom,
    dateTo,
    autoGeneratedOnly,
  ];
}
